import { Country } from './types';

export const countries: Country[] = [
  {
    code: 'KE',
    name: 'Kenya',
    slug: 'kenya',
    capital: 'Nairobi',
    region: 'East Africa',
    provinceCode: 'AFE',
    provinceName: 'Eastern Africa',
    centreCount: 6,
    keyTrades: ['Solar PV Installation', 'Electrical Engineering', 'Automotive Technology', 'Fashion & Design', 'ICT & Software', 'Plumbing'],
    summary: 'Home to the DBTA Continental Secretariat in Nairobi, Kenya features flagship centres including Don Bosco Boys Town Karen, Don Bosco Makuyu, and Don Bosco Embu (Agriculture for Life pilot).',
    featuredCentres: [
      {
        id: 'db-karen',
        name: 'Don Bosco Boys Town Karen',
        city: 'Nairobi',
        countryName: 'Kenya',
        countryCode: 'KE',
        provinceCode: 'AFE',
        courses: ['Electrical Installation', 'Motor Vehicle Mechanics', 'Plumbing', 'Carpentry', 'Tailoring', 'Solar Energy'],
        studentCount: 850,
        establishedYear: 1985,
        isFlagship: true,
        address: 'Karen, Langata Road, Nairobi',
      },
      {
        id: 'db-makuyu',
        name: 'Don Bosco Technical Institute Makuyu',
        city: 'Murang’a / Makuyu',
        countryName: 'Kenya',
        countryCode: 'KE',
        provinceCode: 'AFE',
        courses: ['Welding & Metal Fabrication', 'Building Construction', 'Agriculture', 'ICT'],
        studentCount: 420,
        establishedYear: 1992,
        isFlagship: false,
      },
      {
        id: 'db-embu',
        name: 'Don Bosco Vocational Training Centre Embu',
        city: 'Embu',
        countryName: 'Kenya',
        countryCode: 'KE',
        provinceCode: 'AFE',
        courses: ['Climate-Smart Agriculture', 'Agribusiness', 'Mechanics', 'Electrical'],
        studentCount: 380,
        establishedYear: 2004,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'TZ',
    name: 'Tanzania',
    slug: 'tanzania',
    capital: 'Dodoma',
    region: 'East Africa',
    provinceCode: 'TZA',
    provinceName: 'Tanzania Province',
    centreCount: 5,
    keyTrades: ['Solar Energy', 'Mechanical Engineering', 'Carpentry', 'Electrical Installation', 'Hospitality'],
    summary: 'Salesian TVET centres in Tanzania operate with national VETA accreditation, with premier institutes in Dar es Salaam (Oysterbay), Dodoma, and Iringa.',
    featuredCentres: [
      {
        id: 'db-oysterbay',
        name: 'Don Bosco VTC Oysterbay',
        city: 'Dar es Salaam',
        countryName: 'Tanzania',
        countryCode: 'TZ',
        provinceCode: 'TZA',
        courses: ['Solar PV', 'Electrical', 'Electronics', 'Secretarial & IT', 'Welding'],
        studentCount: 650,
        establishedYear: 1988,
        isFlagship: true,
      },
      {
        id: 'db-dodoma',
        name: 'Don Bosco Technical Institute Dodoma',
        city: 'Dodoma',
        countryName: 'Tanzania',
        countryCode: 'TZ',
        provinceCode: 'TZA',
        courses: ['Motor Vehicle Mechanics', 'Carpentry & Joinery', 'Fitter Mechanics'],
        studentCount: 390,
        establishedYear: 1995,
      },
    ],
  },
  {
    code: 'RW',
    name: 'Rwanda',
    slug: 'rwanda',
    capital: 'Kigali',
    region: 'East Africa',
    provinceCode: 'AGL',
    provinceName: 'Great Lakes (AGL)',
    centreCount: 4,
    keyTrades: ['Hospitality & Culinary Arts', 'Information Technology', 'Plumbing', 'Solar PV', 'Tailoring'],
    summary: 'A leading beacon of modern TVET delivery in Rwanda, renowned for Don Bosco Gatenga and Don Bosco Muhazi focusing on hospitality and renewable technologies.',
    featuredCentres: [
      {
        id: 'db-gatenga',
        name: 'Don Bosco TVET School Gatenga',
        city: 'Kigali',
        countryName: 'Rwanda',
        countryCode: 'RW',
        provinceCode: 'AGL',
        courses: ['Hospitality', 'Culinary Arts', 'Solar PV', 'Plumbing', 'Construction'],
        studentCount: 600,
        establishedYear: 1995,
        isFlagship: true,
      },
      {
        id: 'db-muhazi',
        name: 'Don Bosco TVET Centre Muhazi',
        city: 'Muhazi',
        countryName: 'Rwanda',
        countryCode: 'RW',
        provinceCode: 'AGL',
        courses: ['Culinary Arts', 'Tailoring', 'Masonry', 'Electrical'],
        studentCount: 310,
        establishedYear: 2002,
      },
    ],
  },
  {
    code: 'UG',
    name: 'Uganda',
    slug: 'uganda',
    capital: 'Kampala',
    region: 'East Africa',
    provinceCode: 'AGL',
    provinceName: 'Great Lakes (AGL)',
    centreCount: 4,
    keyTrades: ['Automotive Mechanics', 'Metal Fabrication', 'Agriculture', 'Building Construction'],
    summary: 'Providing critical technical qualifications and refugee youth training across centres in Bombo, Palabek, and Kamuli.',
    featuredCentres: [
      {
        id: 'db-bombo',
        name: 'Don Bosco Vocational Training Centre Bombo',
        city: 'Bombo',
        countryName: 'Uganda',
        countryCode: 'UG',
        provinceCode: 'AGL',
        courses: ['Motor Vehicle Mechanics', 'Electrical Installation', 'Bricklaying', 'Tailoring'],
        studentCount: 450,
        establishedYear: 1997,
        isFlagship: true,
      },
      {
        id: 'db-palabek',
        name: 'Don Bosco Vocational Centre Palabek',
        city: 'Palabek Refugee Settlement',
        countryName: 'Uganda',
        countryCode: 'UG',
        provinceCode: 'AGL',
        courses: ['Solar Installation', 'Motorcycle Mechanics', 'Tailoring', 'Agriculture'],
        studentCount: 520,
        establishedYear: 2018,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'CD',
    name: 'Democratic Republic of the Congo',
    slug: 'drc',
    capital: 'Kinshasa',
    region: 'Central Africa',
    provinceCode: 'AFC',
    provinceName: 'Central Africa (AFC)',
    centreCount: 11,
    keyTrades: ['Industrial Electricity', 'Heavy Mechanics', 'Welding', 'Carpentry', 'Electronics'],
    summary: 'One of the largest Salesian TVET networks on the continent, with massive industrial training institutions in Lubumbashi, Kinshasa, and Goma.',
    featuredCentres: [
      {
        id: 'db-lubumbashi',
        name: 'Institut Technique Salama (ITS)',
        city: 'Lubumbashi',
        countryName: 'Democratic Republic of the Congo',
        countryCode: 'CD',
        provinceCode: 'AFC',
        courses: ['Industrial Electronics', 'General Mechanics', 'Printing & Graphics', 'Automotive'],
        studentCount: 1200,
        establishedYear: 1960,
        isFlagship: true,
      },
      {
        id: 'db-goma',
        name: 'Don Bosco Ngangi VTC',
        city: 'Goma',
        countryName: 'Democratic Republic of the Congo',
        countryCode: 'CD',
        provinceCode: 'AFC',
        courses: ['Welding', 'Carpentry', 'Masonry', 'Tailoring', 'Automotive Repair'],
        studentCount: 950,
        establishedYear: 1998,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'NG',
    name: 'Nigeria',
    slug: 'nigeria',
    capital: 'Abuja',
    region: 'West Africa',
    provinceCode: 'ANN',
    provinceName: 'Nigeria (ANN)',
    centreCount: 6,
    keyTrades: ['Digital Media', 'Automotive Engineering', 'Welding & Fabrication', 'Renewable Energy', 'ICT'],
    summary: 'State-of-the-art training centres in Lagos (Ondo, Akure), Onitsha, and Abuja preparing youth for industrial manufacturing and tech ecosystems.',
    featuredCentres: [
      {
        id: 'db-ondo',
        name: 'Don Bosco Technical Institute Ondo',
        city: 'Ondo State',
        countryName: 'Nigeria',
        countryCode: 'NG',
        provinceCode: 'ANN',
        courses: ['Mechatronics', 'Electrical Installation', 'Welding', 'Computer Science'],
        studentCount: 520,
        establishedYear: 1990,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'GH',
    name: 'Ghana',
    slug: 'ghana',
    capital: 'Accra',
    region: 'West Africa',
    provinceCode: 'AOS',
    provinceName: 'West Africa South (AOS)',
    centreCount: 4,
    keyTrades: ['Solar PV', 'Electrical Wiring', 'Mechanical Engineering', 'Hospitality', 'Fashion'],
    summary: 'Don Bosco TVET institutions in Tema (Ashaiman) and Sunyani deliver internationally recognized vocational diplomas and robust industry linkages.',
    featuredCentres: [
      {
        id: 'db-ashaiman',
        name: 'Don Bosco Technical Institute Ashaiman',
        city: 'Tema / Accra',
        countryName: 'Ghana',
        countryCode: 'GH',
        provinceCode: 'AOS',
        courses: ['Automotive Engineering', 'Electrical & Solar', 'Welding', 'Graphic Design'],
        studentCount: 780,
        establishedYear: 1994,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'ZM',
    name: 'Zambia',
    slug: 'zambia',
    capital: 'Lusaka',
    region: 'Southern Africa',
    provinceCode: 'ZMB',
    provinceName: 'ZMB Vice-Province',
    centreCount: 4,
    keyTrades: ['Solar Power Installation', 'Heavy Metal Fabrication', 'Automotive Repair', 'Agriculture', 'ICT'],
    summary: 'Don Bosco centres in Lusaka (Makeni), Chingola, and Kazembe equip youth for the copperbelt industrial and agricultural job markets.',
    featuredCentres: [
      {
        id: 'db-chingola',
        name: 'Don Bosco Technical College Chingola',
        city: 'Chingola',
        countryName: 'Zambia',
        countryCode: 'ZM',
        provinceCode: 'ZMB',
        courses: ['Automotive Mechanics', 'Metal Fabrication', 'Electrical', 'ICT'],
        studentCount: 460,
        establishedYear: 1989,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'MW',
    name: 'Malawi',
    slug: 'malawi',
    capital: 'Lilongwe',
    region: 'Southern Africa',
    provinceCode: 'ZMB',
    provinceName: 'ZMB Vice-Province',
    centreCount: 3,
    keyTrades: ['Recognition of Prior Learning (RPL)', 'Solar PV', 'Construction', 'Tailoring', 'Agribusiness'],
    summary: 'Pioneering the national Recognition of Prior Learning (RPL) framework with TEVETA Malawi at Don Bosco Youth Technical Institute Lilongwe.',
    featuredCentres: [
      {
        id: 'db-lilongwe',
        name: 'Don Bosco Youth Technical Institute Lilongwe',
        city: 'Lilongwe',
        countryName: 'Malawi',
        countryCode: 'MW',
        provinceCode: 'ZMB',
        courses: ['RPL Artisan Certification', 'Solar PV', 'Fashion Design', 'Motor Vehicle Mechanics', 'Electrical'],
        studentCount: 890,
        establishedYear: 1996,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'MG',
    name: 'Madagascar',
    slug: 'madagascar',
    capital: 'Antananarivo',
    region: 'North Africa & Islands',
    provinceCode: 'MDG',
    provinceName: 'Madagascar (MDG)',
    centreCount: 7,
    keyTrades: ['Agricultural Mechanization', 'Carpentry', 'Electrical Systems', 'Textile Production', 'Masonry'],
    summary: 'Spanning Ivato, Betafo, Fianarantsoa, and Mahajanga, providing agricultural and industrial trades to rural and urban youth.',
    featuredCentres: [
      {
        id: 'db-ivato',
        name: 'Don Bosco Centre Technique Ivato',
        city: 'Antananarivo',
        countryName: 'Madagascar',
        countryCode: 'MG',
        provinceCode: 'MDG',
        courses: ['Metalwork', 'Carpentry', 'Electrical Engineering', 'Auto Mechanics'],
        studentCount: 620,
        establishedYear: 1982,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'MZ',
    name: 'Mozambique',
    slug: 'mozambique',
    capital: 'Maputo',
    region: 'Southern Africa',
    provinceCode: 'MOZ',
    provinceName: 'Mozambique (MOZ)',
    centreCount: 8,
    keyTrades: ['Electrical Building Systems', 'Solar Installation', 'Metalwork', 'Carpentry', 'IT Services'],
    summary: 'Prominent institutions in Maputo, Moamba, Inharrime, and Quelimane supporting post-conflict vocational recovery and youth trades.',
    featuredCentres: [
      {
        id: 'db-maputo',
        name: 'Escola Profissional Dom Bosco Maputo',
        city: 'Maputo',
        countryName: 'Mozambique',
        countryCode: 'MZ',
        provinceCode: 'MOZ',
        courses: ['Electrical Installation', 'Solar PV', 'Metal Mechanics', 'Computer Maintenance'],
        studentCount: 710,
        establishedYear: 1991,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    slug: 'burkina-faso',
    capital: 'Ouagadougou',
    region: 'West Africa',
    provinceCode: 'AON',
    provinceName: 'West Africa North (AON)',
    centreCount: 3,
    keyTrades: ['Solar Pumping (SPVWPS)', 'Recognition of Prior Learning', 'Automotive', 'Masonry'],
    summary: 'A focal hub for solar water pumping systems and RPL framework development in the Sahel region.',
    featuredCentres: [
      {
        id: 'db-ouaga',
        name: 'Centre Professionnel Don Bosco Ouagadougou',
        city: 'Ouagadougou',
        countryName: 'Burkina Faso',
        countryCode: 'BF',
        provinceCode: 'AON',
        courses: ['Solar PV Water Systems', 'RPL Certifications', 'Automotive', 'Welding'],
        studentCount: 480,
        establishedYear: 1993,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    slug: 'ethiopia',
    capital: 'Addis Ababa',
    region: 'East Africa',
    provinceCode: 'AET',
    provinceName: 'Ethiopia & Eritrea (AET)',
    centreCount: 6,
    keyTrades: ['Industrial Electronics', 'Graphic Design', 'Leather Goods', 'General Mechanics', 'Woodworking'],
    summary: 'High-enrollment technical colleges located in Addis Ababa (Mekanissa), Adigrat, and Dilla providing dual technical certifications.',
    featuredCentres: [
      {
        id: 'db-mekanissa',
        name: 'Don Bosco Technical College Mekanissa',
        city: 'Addis Ababa',
        countryName: 'Ethiopia',
        countryCode: 'ET',
        provinceCode: 'AET',
        courses: ['Graphic Communication', 'Industrial Mechanics', 'Electronics', 'Drafting'],
        studentCount: 800,
        establishedYear: 1987,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'AO',
    name: 'Angola',
    slug: 'angola',
    capital: 'Luanda',
    region: 'Southern Africa',
    provinceCode: 'ANG',
    provinceName: 'Angola (ANG)',
    centreCount: 7,
    keyTrades: ['Industrial Electricity', 'Plumbing', 'Automobile Mechanics', 'Computing', 'Civil Construction'],
    summary: 'Centres in Luanda (Cazenga, Sambizanga) and Benguela offering technical skills to underprivileged urban youth.',
    featuredCentres: [
      {
        id: 'db-cazenga',
        name: 'Centro de Formação Profissional Dom Bosco Cazenga',
        city: 'Luanda',
        countryName: 'Angola',
        countryCode: 'AO',
        provinceCode: 'ANG',
        courses: ['Industrial Electricity', 'Plumbing', 'Refrigeration', 'Auto Mechanics'],
        studentCount: 650,
        establishedYear: 1988,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'ZA',
    name: 'South Africa',
    slug: 'south-africa',
    capital: 'Pretoria',
    region: 'Southern Africa',
    provinceCode: 'AFM',
    provinceName: 'Southern Africa (AFM)',
    centreCount: 3,
    keyTrades: ['Solar Power & Green Energy', 'Mechatronics', 'Youth Entrepreneurship', 'Welding'],
    summary: 'Don Bosco centres in Ennerdale and Cape Town driving green economy skills and youth job readiness.',
    featuredCentres: [
      {
        id: 'db-ennerdale',
        name: 'Don Bosco Youth Centre Ennerdale',
        city: 'Johannesburg',
        countryName: 'South Africa',
        countryCode: 'ZA',
        provinceCode: 'AFM',
        courses: ['Solar Energy', 'Welding', 'Life Skills & Job Readiness', 'ICT'],
        studentCount: 320,
        establishedYear: 1993,
        isFlagship: true,
      },
    ],
  },
  {
    code: 'SN',
    name: 'Senegal',
    slug: 'senegal',
    capital: 'Dakar',
    region: 'West Africa',
    provinceCode: 'AON',
    provinceName: 'West Africa North (AON)',
    centreCount: 2,
    keyTrades: ['Metalwork', 'Electrical', 'Carpentry', 'Digital Skills'],
    summary: 'Don Bosco centres in Dakar (Thiaroye) providing vocational alternatives and migration prevention training for youth.',
    featuredCentres: [],
  },
  {
    code: 'CI',
    name: "Cote d'Ivoire",
    slug: 'cote-divoire',
    capital: 'Yamoussoukro',
    region: 'West Africa',
    provinceCode: 'AON',
    provinceName: 'West Africa North (AON)',
    centreCount: 2,
    keyTrades: ['Auto Mechanics', 'Electrical Systems', 'Agriculture', 'Tailoring'],
    summary: 'Centres in Abidjan and Korhogo equipping young people with modern market-ready vocational skills.',
    featuredCentres: [],
  },
  {
    code: 'CM',
    name: 'Cameroon',
    slug: 'cameroon',
    capital: 'Yaoundé',
    region: 'Central Africa',
    provinceCode: 'ATE',
    provinceName: 'Equatorial Tropical Africa (ATE)',
    centreCount: 3,
    keyTrades: ['Carpentry & Joinery', 'Electrical', 'Auto Mechanics', 'Plumbing'],
    summary: 'Institutes in Yaoundé and Ebolowa providing technical and vocational certifications for Central African youth.',
    featuredCentres: [],
  },
  {
    code: 'SS',
    name: 'South Sudan',
    slug: 'south-sudan',
    capital: 'Juba',
    region: 'East Africa',
    provinceCode: 'AFE',
    provinceName: 'Eastern Africa (AFE)',
    centreCount: 3,
    keyTrades: ['Building Construction', 'Solar Installation', 'Automotive Repair', 'Tailoring'],
    summary: 'Centres in Juba, Wau, and Tonj providing essential post-conflict vocational skills and emergency livelihoods training.',
    featuredCentres: [],
  },
  {
    code: 'BI',
    name: 'Burundi',
    slug: 'burundi',
    capital: 'Gitega',
    region: 'East Africa',
    provinceCode: 'AGL',
    provinceName: 'Great Lakes (AGL)',
    centreCount: 3,
    keyTrades: ['Masonry', 'Electrical', 'Carpentry', 'Agronomy'],
    summary: 'Don Bosco institutions in Ngozi and Buterere providing youth skills for regional employment and self-reliance.',
    featuredCentres: [],
  },
  {
    code: 'SL',
    name: 'Sierra Leone',
    slug: 'sierra-leone',
    capital: 'Freetown',
    region: 'West Africa',
    provinceCode: 'AOS',
    provinceName: 'West Africa South (AOS)',
    centreCount: 2,
    keyTrades: ['Catering', 'Electrical Wiring', 'Tailoring', 'Computer Software'],
    summary: 'Don Bosco Fambul in Freetown offering vocational shelter and skills training to street-connected and vulnerable youth.',
    featuredCentres: [],
  },
  {
    code: 'LR',
    name: 'Liberia',
    slug: 'liberia',
    capital: 'Monrovia',
    region: 'West Africa',
    provinceCode: 'AOS',
    provinceName: 'West Africa South (AOS)',
    centreCount: 2,
    keyTrades: ['Plumbing', 'Auto Mechanics', 'Electrical', 'Drafting'],
    summary: 'Centres in Monrovia equipping young Liberians with sustainable trade competencies.',
    featuredCentres: [],
  },
  {
    code: 'TG',
    name: 'Togo',
    slug: 'togo',
    capital: 'Lomé',
    region: 'West Africa',
    provinceCode: 'AON',
    provinceName: 'West Africa North (AON)',
    centreCount: 2,
    keyTrades: ['Carpentry', 'Industrial Electricity', 'Metalwork', 'ICT'],
    summary: 'Centres in Lomé offering French-certified vocational programs in construction and technical trades.',
    featuredCentres: [],
  },
  {
    code: 'BJ',
    name: 'Benin',
    slug: 'benin',
    capital: 'Porto-Novo',
    region: 'West Africa',
    provinceCode: 'AON',
    provinceName: 'West Africa North (AON)',
    centreCount: 2,
    keyTrades: ['Renewable Energy', 'Automobile Maintenance', 'Tailoring', 'Metalwork'],
    summary: 'Don Bosco centres in Cotonou and Parakou training youth in technical and artisanal crafts.',
    featuredCentres: [],
  },
  {
    code: 'ML',
    name: 'Mali',
    slug: 'mali',
    capital: 'Bamako',
    region: 'West Africa',
    provinceCode: 'AON',
    provinceName: 'West Africa North (AON)',
    centreCount: 2,
    keyTrades: ['Solar Power Installation', 'Mechanics', 'Carpentry'],
    summary: 'Centres in Bamako and Touba delivering vocational instruction in electrical systems and clean energy.',
    featuredCentres: [],
  },
  {
    code: 'ZW',
    name: 'Zimbabwe',
    slug: 'zimbabwe',
    capital: 'Harare',
    region: 'Southern Africa',
    provinceCode: 'ZMB',
    provinceName: 'ZMB Vice-Province',
    centreCount: 2,
    keyTrades: ['Motor Vehicle Mechanics', 'Welding', 'ICT', 'Agriculture'],
    summary: 'Don Bosco Technical College in Hwange training young artisans in engineering and industrial manufacturing.',
    featuredCentres: [],
  },
  {
    code: 'SD',
    name: 'Sudan',
    slug: 'sudan',
    capital: 'Khartoum',
    region: 'East Africa',
    provinceCode: 'AFE',
    provinceName: 'Eastern Africa (AFE)',
    centreCount: 2,
    keyTrades: ['General Mechanics', 'Electrical Installation', 'Woodworking'],
    summary: 'Centres in Khartoum (St. Joseph VTC) supporting technical education for underprivileged youth.',
    featuredCentres: [],
  },
  {
    code: 'CG',
    name: 'Republic of the Congo',
    slug: 'republic-of-congo',
    capital: 'Brazzaville',
    region: 'Central Africa',
    provinceCode: 'ACC',
    provinceName: 'Congo (ACC)',
    centreCount: 3,
    keyTrades: ['Masonry', 'Electrical', 'Metal Fabrication', 'ICT'],
    summary: 'Institutions in Brazzaville and Pointe-Noire offering accredited technical diplomas.',
    featuredCentres: [],
  },
  {
    code: 'TD',
    name: 'Chad',
    slug: 'chad',
    capital: "N'Djamena",
    region: 'Central Africa',
    provinceCode: 'ATE',
    provinceName: 'Equatorial Tropical Africa (ATE)',
    centreCount: 2,
    keyTrades: ['Carpentry', 'Welding', 'Solar Energy', 'Agriculture'],
    summary: 'Vocational training centres in Sarh providing technical livelihoods to youth in the Sahel.',
    featuredCentres: [],
  },
  {
    code: 'CF',
    name: 'Central African Republic',
    slug: 'car',
    capital: 'Bangui',
    region: 'Central Africa',
    provinceCode: 'ATE',
    provinceName: 'Equatorial Tropical Africa (ATE)',
    centreCount: 2,
    keyTrades: ['Building Construction', 'Carpentry', 'Auto Mechanics', 'Electrical'],
    summary: 'Don Bosco Damala in Bangui providing vital vocational recovery and youth peacebuilding skills.',
    featuredCentres: [],
  },
  {
    code: 'GA',
    name: 'Gabon',
    slug: 'gabon',
    capital: 'Libreville',
    region: 'Central Africa',
    provinceCode: 'ATE',
    provinceName: 'Equatorial Tropical Africa (ATE)',
    centreCount: 1,
    keyTrades: ['Electricity', 'Plumbing', 'Carpentry', 'IT Services'],
    summary: 'Vocational institute in Libreville providing market-aligned training.',
    featuredCentres: [],
  },
  {
    code: 'GQ',
    name: 'Equatorial Guinea',
    slug: 'equatorial-guinea',
    capital: 'Malabo',
    region: 'Central Africa',
    provinceCode: 'ATE',
    provinceName: 'Equatorial Tropical Africa (ATE)',
    centreCount: 1,
    keyTrades: ['Electrical Wiring', 'Mechanics', 'Carpentry'],
    summary: 'Vocational training centre in Malabo providing technical education.',
    featuredCentres: [],
  },
  {
    code: 'LS',
    name: 'Lesotho',
    slug: 'lesotho',
    capital: 'Maseru',
    region: 'Southern Africa',
    provinceCode: 'AFM',
    provinceName: 'Southern Africa (AFM)',
    centreCount: 1,
    keyTrades: ['Building & Construction', 'Motor Mechanics', 'Tailoring'],
    summary: 'Centres in Maputsoe providing skills and life mentoring to Basotho youth.',
    featuredCentres: [],
  },
  {
    code: 'SZ',
    name: 'Eswatini',
    slug: 'eswatini',
    capital: 'Mbabane',
    region: 'Southern Africa',
    provinceCode: 'AFM',
    provinceName: 'Southern Africa (AFM)',
    centreCount: 1,
    keyTrades: ['Agriculture', 'Electrical', 'Metalwork', 'Carpentry'],
    summary: 'Don Bosco Youth Centre in Malkerns providing agricultural and industrial artisan training.',
    featuredCentres: [],
  },
  {
    code: 'MU',
    name: 'Mauritius',
    slug: 'mauritius',
    capital: 'Port Louis',
    region: 'North Africa & Islands',
    provinceCode: 'MDG',
    provinceName: 'Madagascar (MDG)',
    centreCount: 1,
    keyTrades: ['Hospitality & Tourism', 'IT Systems', 'Electrical'],
    summary: 'Don Bosco technical school in Port Louis preparing youth for island service economies.',
    featuredCentres: [],
  },
];
