import { DigitalService } from './types';

export const digitalServices: DigitalService[] = [
  {
    id: 'tvet-center-portal',
    name: 'DBTVET Center Portal',
    badge: 'Institutional Management',
    description: 'Centralized institutional database connecting 119 TVET institutions for curriculum records, student registrations, centre facilities audit, and accredited trade listings.',
    targetAudience: 'TVET Centre Directors, Registrars, Provincial Coordinators',
    keyFeatures: [
      'Comprehensive centre profile and trade accreditation records',
      'Student enrollment and completion logs',
      'Workshop machinery and didactic equipment telemetry',
      'Harmonized assessment scoring and examination records',
    ],
    url: 'https://tvet.dbtechafrica.org/',
    iconName: 'Building2',
    status: 'Live & Operational',
  },
  {
    id: 'digital-library',
    name: 'DBTA Digital Library',
    badge: 'Open Learning Gateway',
    description: 'Cloud repository hosting thousands of digitized textbooks, instructional slides, standardized trade syllabi, and multi-media learning assets accessible across English, French, and Portuguese.',
    targetAudience: 'TVET Instructors, Students, Academic Researchers',
    keyFeatures: [
      'Over 2,500 curated vocational manuals and trade textbooks',
      'Categorized trade libraries (Solar, Mechanical, Automotive, ICT, Agriculture)',
      'Offline caching capabilities for low-bandwidth rural institutions',
      'Free open-access repository for Salesian learning communities',
    ],
    url: 'https://www.digitallibrary.dbtechafrica.org/',
    iconName: 'BookOpen',
    status: 'Live & Operational',
  },
  {
    id: 'inserjeune-tracer',
    name: 'Inserjeune Job Placement Tracer',
    badge: 'Graduate Tracking & Employment',
    description: 'The continental tracer study platform enabling Job Service Offices (JSOs) to match graduates with vetted employers and track career trajectories post-graduation.',
    targetAudience: 'Job Service Officers (JSOs), Graduates, Corporate Employers',
    keyFeatures: [
      'Automated 6-month, 1-year, and 2-year graduate employment surveys',
      'Direct employer recruitment portal and vacancy matching',
      'Real-time labor market analytics and skill demand indices',
      'Alumni entrepreneurship tracking and mentoring link',
    ],
    url: 'https://dbtechafricatracer.org/',
    iconName: 'Briefcase',
    status: 'Live & Operational',
  },
  {
    id: 'staff-portal',
    name: 'DBTA Staff & Operations Portal',
    badge: 'Internal Secretariat System',
    description: 'Unified operational workspace for DBTA secretariat teams, multi-country project officers, financial controllers, and governance committees.',
    targetAudience: 'DBTA Staff, Project Managers, Provincial Coordinators',
    keyFeatures: [
      'Secure project milestones and financial procurement tracking',
      'Document sharing and collaborative committee workspaces',
      'Internal communication and policy repository',
      'Multi-currency budget monitoring and audit compliance',
    ],
    url: 'https://office.dbtechafrica.org/',
    iconName: 'Lock',
    status: 'Live & Operational',
  },
  {
    id: 'instructional-toolkit',
    name: 'DBTA Instructional Toolkit Platform',
    badge: 'Standard Operating Procedures',
    description: 'Specialized practitioner repository housing Quality Management System (QMS) audit templates, workshop safety checklists, and RPL assessment protocols.',
    targetAudience: 'Quality Assurance Officers, TVET Assessors, Workshop Technicians',
    keyFeatures: [
      'QMS audit matrices and compliance assessment rubrics',
      'Standard Operating Procedures (SOPs) for vocational workshops',
      'RPL diagnostic portfolio templates and scoring keys',
      'Green TVET campus sustainability evaluation checklists',
    ],
    url: 'https://toolkit.dbtechafrica.org/',
    iconName: 'Wrench',
    status: 'Live & Operational',
  },
  {
    id: 'dbvti-platform',
    name: 'DBVTI Vocational Institute Gateway',
    badge: 'Virtual Institute',
    description: 'Dedicated virtual training portal supporting hybrid vocational coursework, instructor certification tracks, and distance learning programs.',
    targetAudience: 'Master Trainers, Advanced Vocational Students',
    keyFeatures: [
      'Modular virtual learning environment for instructor pedagogical upskilling',
      'Blended learning modules in renewable energy and digital literacy',
      'Interactive assessments and digital credential issuance',
    ],
    url: 'https://dbvti.dbtechafrica.org/',
    iconName: 'GraduationCap',
    status: 'Live & Operational',
  },
];
