import { DBTAEvent } from './types';

export const dbtaEvents: DBTAEvent[] = [
  {
    id: 'continental-tvet-teachers-training-2026',
    slug: 'teachers-training',
    title: 'Continental TVET Instructors Pedagogical & Technical Training Workshop',
    date: '2026-05-01',
    startDate: '2026-05-01',
    endDate: '2026-05-06',
    location: 'Nairobi, Kenya & Online Hybrid',
    type: 'Training Workshop',
    category: 'Pedagogical Training',
    status: 'Upcoming',
    isOnline: true,
    targetAudience: 'TVET Centre Instructors, Department Heads, and Master Trainers from all 15 Salesian Provinces.',
    featuredImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Quality-Education-Innovation.png',
    description: 'Annual continental capacity building seminar focusing on competency-based curriculum delivery, digital simulator integration, and modern workshop safety management for Salesian TVET instructors.',
    isUpcoming: true,
    registrationUrl: '/contact?intent=event',
  },
  {
    id: 'annual-stakeholders-assembly-2026',
    slug: 'annual-stakeholders-assembly-2026',
    title: 'Don Bosco Tech Africa Annual Stakeholders Assembly (ASA 2026)',
    date: '2026-10-15',
    startDate: '2026-10-15',
    endDate: '2026-10-17',
    location: 'Kigali, Rwanda & Virtual Livestream',
    type: 'Annual Stakeholders Assembly',
    category: 'Continental Governance',
    status: 'Upcoming',
    isOnline: true,
    targetAudience: 'Salesian Provincials, TVET Principals, International Donors (BMZ, Don Bosco Mondo), AU & national TVET authorities.',
    featuredImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Pan-African-Network.png',
    description: 'The premier continental governance and partnership convocation uniting Salesian Provincials, TVET Principals, international development partners, and employer federations.',
    isUpcoming: true,
    registrationUrl: '/contact?intent=event',
  },
  {
    id: 'green-tvet-solar-specialists-masterclass',
    slug: 'green-tvet-solar-specialists-masterclass',
    title: 'Regional Solar PV & Water Pumping Masterclass for TVET Master Trainers',
    date: '2026-11-20',
    startDate: '2026-11-20',
    endDate: '2026-11-24',
    location: 'Accra, Ghana (Don Bosco Ashaiman)',
    type: 'Training Workshop',
    category: 'Green TVET & Renewable Energy',
    status: 'Upcoming',
    isOnline: false,
    targetAudience: 'Electrical and Solar PV Instructors in West & Central Africa provinces.',
    featuredImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Hands-On-Technical-Training.png',
    description: 'Advanced hands-on technical masterclass on sizing, testing, and installing high-capacity Solar Photovoltaic Water Pumping Systems (SPVWPS) for agricultural and commercial applications.',
    isUpcoming: true,
    registrationUrl: '/contact?intent=event',
  },
];

export const events = dbtaEvents;
