import { InstitutionBenchmark } from './types';

export const institutions: InstitutionBenchmark[] = [
  {
    id: 'db-boys-town-nairobi',
    slug: 'don-bosco-boys-town-nairobi',
    name: 'Don Bosco Boys Town Technical Institute',
    shortName: 'Boys Town Nairobi',
    city: 'Nairobi',
    countryName: 'Kenya',
    countryCode: 'KE',
    flagEmoji: '🇰🇪',
    provinceCode: 'AFE',
    provinceName: 'Eastern Africa',
    tier: 'Tier 1 - Center of Excellence',
    overallScore: 94.2,
    rankBand: '#1',
    establishedYear: 1985,
    metrics: {
      employmentRate: 88,
      annualTrainees: 1450,
      femaleEnrollmentPct: 41,
      greenTVETRating: 'Gold',
      industryPartnerships: 32,
      workshopQualityScore: 96,
    },
    keyTrades: ['Solar PV & Microgrids', 'Automotive Mechatronics', 'Industrial Electrical', 'Welding & Fabrication', 'Plumbing'],
    tradeIds: ['solar-pv', 'automotive-mechatronics', 'electrical-installation', 'welding-fabrication'],
    facilities: [
      'Schneider Electric Green Innovation Lab',
      'Bosch-Certified Diagnostic Automotive Workshop',
      'Industrial PLC Automation Suite',
      'Solar Rooftop Grid-Tie Test Facility (50kWp)',
    ],
    accreditationBody: 'TVETA (Technical and Vocational Education and Training Authority, Kenya)',
    leadPartners: ['Schneider Electric Foundation', 'Don Bosco Mondo', 'BMZ Germany'],
    contact: {
      email: 'principal@donboscoboystown.org',
      phone: '+254 20 204 4300',
      website: 'https://donboscoboystown.org',
      address: 'Langata South Road, Karen, P.O. Box 24423-00502, Nairobi, Kenya',
    },
    summary:
      'Premier continental Center of Excellence in renewable energy, solar PV microgrids, and automotive mechatronics with an audited 88% graduate placement rate within 6 months of qualification.',
    featured: true,
  },
  {
    id: 'db-gatenga-kigali',
    slug: 'don-bosco-gatenga-kigali',
    name: 'Don Bosco Gatenga TVET Center',
    shortName: 'DB Gatenga Kigali',
    city: 'Kigali',
    countryName: 'Rwanda',
    countryCode: 'RW',
    flagEmoji: '🇷🇼',
    provinceCode: 'AGL',
    provinceName: 'Great Lakes',
    tier: 'Tier 1 - Center of Excellence',
    overallScore: 91.8,
    rankBand: '#2',
    establishedYear: 1993,
    metrics: {
      employmentRate: 85,
      annualTrainees: 1100,
      femaleEnrollmentPct: 46,
      greenTVETRating: 'Gold',
      industryPartnerships: 26,
      workshopQualityScore: 92,
    },
    keyTrades: ['Renewable Energy', 'ICT & Software Skills', 'Carpentry & Modern Joinery', 'Culinary & Hospitality', 'Plumbing'],
    tradeIds: ['solar-pv', 'ict-software', 'modern-woodworking', 'hospitality-culinary'],
    facilities: [
      'Green TVET Biogas & Solar Demonstration Unit',
      'Modern High-Precision Woodworking CNC Plant',
      'Certified Cisco & Digital Networking Hub',
      'Smart Hospitality Culinary Demonstration Kitchen',
    ],
    accreditationBody: 'Rwanda TVET Board (RTB)',
    leadPartners: ['Misereor', 'Swisscontact', 'Mastercard Foundation'],
    contact: {
      email: 'gatenga@dbtechafrica.org',
      phone: '+250 788 304 901',
      address: 'Kicukiro District, Gatenga Sector, Kigali, Rwanda',
    },
    summary:
      'Pioneering sustainable vocational education and female empowerment in STEM across the Great Lakes region, with nationally benchmarked programs in solar energy and modern woodworking.',
    featured: true,
  },
  {
    id: 'db-ashaiman-accra',
    slug: 'don-bosco-ashaiman-ghana',
    name: 'Don Bosco Technical Institute Ashaiman',
    shortName: 'DB Ashaiman Accra',
    city: 'Ashaiman / Accra',
    countryName: 'Ghana',
    countryCode: 'GH',
    flagEmoji: '🇬🇭',
    provinceCode: 'AOS',
    provinceName: 'West Africa South',
    tier: 'Tier 1 - Center of Excellence',
    overallScore: 89.6,
    rankBand: '#3',
    establishedYear: 2002,
    metrics: {
      employmentRate: 82,
      annualTrainees: 980,
      femaleEnrollmentPct: 37,
      greenTVETRating: 'Gold',
      industryPartnerships: 21,
      workshopQualityScore: 90,
    },
    keyTrades: ['Solar PV Installation', 'Electrical Engineering', 'Mechanical Maintenance', 'Printing & Media Technology', 'HVAC'],
    tradeIds: ['solar-pv', 'electrical-installation', 'mechanical-engineering', 'printing-media'],
    facilities: [
      'West Africa Regional Solar Photovoltaic Center',
      'High-Speed Offset & Digital Publishing Lab',
      'Industrial Refrigeration & Heat Pump Rig',
      'Electrical Machine Drives Laboratory',
    ],
    accreditationBody: 'Commission for TVET (CTVET, Ghana)',
    leadPartners: ['Schneider Electric', 'Don Bosco Jugendhilfe Weltweit (JuWe)', 'BMZ'],
    contact: {
      email: 'ashaiman@donboscogh.org',
      phone: '+233 303 304 242',
      address: 'P.O. Box Co 1572, Tema / Ashaiman, Greater Accra, Ghana',
    },
    summary:
      'The leading vocational hub in coastal West Africa for electrical energy, industrial cooling, and graphic media technology, training over 900 young specialists annually.',
    featured: true,
  },
  {
    id: 'db-salama-lubumbashi',
    slug: 'don-bosco-salama-lubumbashi',
    name: 'Institut Technique Salama (Don Bosco)',
    shortName: 'IT Salama Lubumbashi',
    city: 'Lubumbashi',
    countryName: 'Democratic Republic of the Congo',
    countryCode: 'CD',
    flagEmoji: '🇨🇩',
    provinceCode: 'AFC',
    provinceName: 'Central Africa',
    tier: 'Tier 1 - Center of Excellence',
    overallScore: 88.4,
    rankBand: '#4',
    establishedYear: 1961,
    metrics: {
      employmentRate: 84,
      annualTrainees: 1600,
      femaleEnrollmentPct: 29,
      greenTVETRating: 'Silver',
      industryPartnerships: 34,
      workshopQualityScore: 93,
    },
    keyTrades: ['Industrial Electricity', 'General Mechanics & Turning', 'Electronics & Telecommunications', 'Mining Equipment Maintenance', 'Printing'],
    tradeIds: ['electrical-installation', 'mechanical-engineering', 'industrial-automation'],
    facilities: [
      'Heavy Industrial Lathe & Milling Machining Bay',
      'High-Voltage Electrical Distribution Test Bench',
      'Hydraulics & Heavy Pneumatics Testing Cell',
      'Digital Automation Laboratory',
    ],
    accreditationBody: 'Ministère de l’Enseignement Primaire, Secondaire et Technique (EPST, RDC)',
    leadPartners: ['Mining Industry Operators Katanga', 'Don Bosco Mondo', 'ACTEC Belgium'],
    contact: {
      email: 'salama@salesiens-afc.org',
      phone: '+243 997 021 345',
      address: 'Avenue Likasi No. 12, Lubumbashi, Haut-Katanga, RDC',
    },
    summary:
      'Historic heavy-industry training pillar in the Central African mining belt, producing elite electro-mechanics and industrial technicians sought after by mining and infrastructure conglomerates.',
    featured: true,
  },
  {
    id: 'db-dodoma-tanzania',
    slug: 'don-bosco-dodoma-tanzania',
    name: 'Don Bosco Vocational Training Centre Dodoma',
    shortName: 'DB VTC Dodoma',
    city: 'Dodoma',
    countryName: 'Tanzania',
    countryCode: 'TZ',
    flagEmoji: '🇹🇿',
    provinceCode: 'AFE',
    provinceName: 'Eastern Africa',
    tier: 'Tier 2 - Regional Hub',
    overallScore: 86.9,
    rankBand: '#5',
    establishedYear: 1989,
    metrics: {
      employmentRate: 79,
      annualTrainees: 850,
      femaleEnrollmentPct: 39,
      greenTVETRating: 'Gold',
      industryPartnerships: 19,
      workshopQualityScore: 87,
    },
    keyTrades: ['Solar Energy Systems', 'Masonry & Construction', 'Automotive Mechanics', 'Tailoring & Garment Making', 'Secretarial & ICT'],
    tradeIds: ['solar-pv', 'automotive-mechatronics', 'civil-construction'],
    facilities: [
      'Central Tanzania Solar Training Hub',
      'Automotive Mechanical Service Bay',
      'Garment Design & Industrial Sewing Plant',
      'Computerized Drafting (CAD) Lab',
    ],
    accreditationBody: 'VETA (Vocational Educational and Training Authority, Tanzania)',
    leadPartners: ['Misereor', 'VIS Italy', 'Eni Foundation'],
    contact: {
      email: 'dodoma@donbosco.or.tz',
      phone: '+255 26 232 1435',
      address: 'P.O. Box 284, Dodoma, Tanzania',
    },
    summary:
      'Central Tanzanian vocational stronghold with deep community ties, renowned for solar technician certifications and civil construction trades aligned to national infrastructure projects.',
    featured: true,
  },
  {
    id: 'db-thies-senegal',
    slug: 'don-bosco-thies-senegal',
    name: 'Centre de Formation Professionnelle Don Bosco Thiès',
    shortName: 'CFP DB Thiès',
    city: 'Thiès',
    countryName: 'Senegal',
    countryCode: 'SN',
    flagEmoji: '🇸🇳',
    provinceCode: 'AON',
    provinceName: 'West Africa North',
    tier: 'Tier 2 - Regional Hub',
    overallScore: 85.3,
    rankBand: '#6',
    establishedYear: 1991,
    metrics: {
      employmentRate: 77,
      annualTrainees: 740,
      femaleEnrollmentPct: 34,
      greenTVETRating: 'Silver',
      industryPartnerships: 17,
      workshopQualityScore: 86,
    },
    keyTrades: ['Electro-Mechanics', 'Carpentry & Joinery', 'Automotive Repair', 'Agro-Equipment Maintenance', 'Metal Fabrication'],
    tradeIds: ['electrical-installation', 'mechanical-engineering', 'modern-woodworking'],
    facilities: [
      'Francophone West Africa Electro-Technical Lab',
      'Modern Woodworking Machinery Center',
      'Agricultural Machinery Repair Bay',
    ],
    accreditationBody: 'Ministère de la Formation Professionnelle, de l’Apprentissage et de l’Insertion (MFPAI)',
    leadPartners: ['LuxDev', 'Salesian Missions USA', 'Don Bosco Mondo'],
    contact: {
      email: 'thies@donbosco.sn',
      phone: '+221 33 951 1234',
      address: 'Quartier Som, Route de Dakar, Thiès, Sénégal',
    },
    summary:
      'A leading Francophone technical academy preparing youth for modern agricultural modernization, mechanical fabrication, and residential electrical networks.',
    featured: false,
  },
  {
    id: 'db-fianarantsoa-madagascar',
    slug: 'don-bosco-fianarantsoa-madagascar',
    name: 'Centre de Formation Professionnelle Don Bosco Fianarantsoa',
    shortName: 'DB Fianarantsoa',
    city: 'Fianarantsoa',
    countryName: 'Madagascar',
    countryCode: 'MG',
    flagEmoji: '🇲🇬',
    provinceCode: 'MDG',
    provinceName: 'Madagascar',
    tier: 'Tier 2 - Regional Hub',
    overallScore: 84.7,
    rankBand: '#7',
    establishedYear: 1988,
    metrics: {
      employmentRate: 76,
      annualTrainees: 920,
      femaleEnrollmentPct: 44,
      greenTVETRating: 'Gold',
      industryPartnerships: 15,
      workshopQualityScore: 85,
    },
    keyTrades: ['Agro-Ecology & Horticulture', 'Carpentry & Bamboo Engineering', 'Solar Rural Electrification', 'Automotive Mechanics', 'Masonry'],
    tradeIds: ['agribusiness-food', 'modern-woodworking', 'solar-pv'],
    facilities: [
      'Organic Agro-Ecology Demonstration Farm',
      'Bamboo Furniture & Treatment Kiln',
      'Decentralized Rural Solar Mini-Grid Trainer',
    ],
    accreditationBody: 'Ministère de l’Enseignement Technique et de la Formation Professionnelle (METFP, Madagascar)',
    leadPartners: ['European Union Delegation Madagascar', 'VIS Italy', 'FAO'],
    contact: {
      email: 'fianar@dbtechmadagascar.org',
      phone: '+261 20 75 506 20',
      address: 'BP 1150, Fianarantsoa 301, Madagascar',
    },
    summary:
      'Island leader in ecological TVET, circular economy woodworking, and off-grid solar installation, serving rural youths across central and southern Madagascar.',
    featured: false,
  },
  {
    id: 'db-onitsha-nigeria',
    slug: 'don-bosco-onitsha-nigeria',
    name: 'Don Bosco Vocational Training Center Onitsha',
    shortName: 'DB VTC Onitsha',
    city: 'Onitsha',
    countryName: 'Nigeria',
    countryCode: 'NG',
    flagEmoji: '🇳🇬',
    provinceCode: 'AOS',
    provinceName: 'West Africa South',
    tier: 'Tier 2 - Regional Hub',
    overallScore: 83.9,
    rankBand: '#8',
    establishedYear: 2005,
    metrics: {
      employmentRate: 81,
      annualTrainees: 650,
      femaleEnrollmentPct: 32,
      greenTVETRating: 'Silver',
      industryPartnerships: 22,
      workshopQualityScore: 84,
    },
    keyTrades: ['Industrial Electrical', 'Solar PV Design', 'Welding & Pipefitting', 'Computer Hardware & Networking', 'Drafting'],
    tradeIds: ['electrical-installation', 'solar-pv', 'welding-fabrication', 'ict-software'],
    facilities: [
      'Industrial Pipefitting & TIG Welding Lab',
      'Schneider-Equipped Electrical Distribution Rig',
      'Computer Networking & Hardware Laboratory',
    ],
    accreditationBody: 'National Board for Technical Education (NBTE, Nigeria)',
    leadPartners: ['Schneider Electric Nigeria', 'Federal Ministry of Youth', 'Don Bosco Mondo'],
    contact: {
      email: 'onitsha@donbosconigeria.org',
      phone: '+234 803 720 1192',
      address: 'Ogbaru LGA, Near Onitsha Commercial Hub, Anambra State, Nigeria',
    },
    summary:
      'Dynamically situated in the commercial crossroads of eastern Nigeria, training technicians in industrial pipework, solar inverters, and electrical reticulation.',
    featured: false,
  },
  {
    id: 'db-lilongwe-malawi',
    slug: 'don-bosco-youth-technical-institute-lilongwe',
    name: 'Don Bosco Youth Technical Institute Lilongwe',
    shortName: 'DB YTI Lilongwe',
    city: 'Lilongwe',
    countryName: 'Malawi',
    countryCode: 'MW',
    flagEmoji: '🇲🇼',
    provinceCode: 'ZMB',
    provinceName: 'Zambia-Malawi-Zimbabwe-Namibia',
    tier: 'Tier 1 - Center of Excellence',
    overallScore: 87.5,
    rankBand: '#9',
    establishedYear: 2000,
    metrics: {
      employmentRate: 80,
      annualTrainees: 1050,
      femaleEnrollmentPct: 48,
      greenTVETRating: 'Gold',
      industryPartnerships: 25,
      workshopQualityScore: 89,
    },
    keyTrades: ['Solar Energy & Electrical', 'Information Technology', 'Fashion & Garment Technology', 'Automobile Mechanics', 'Accounting & Secretarial'],
    tradeIds: ['solar-pv', 'ict-software', 'electrical-installation'],
    facilities: [
      'Modern Solar & Clean Cookstove Testing Station',
      'Cisco Networking Academy and Software Lab',
      'Industrial Garment Manufacturing Workshop',
    ],
    accreditationBody: 'TEVETA (Technical, Entrepreneurial and Vocational Education and Training Authority, Malawi)',
    leadPartners: ['BMZ Germany', 'Don Bosco Mondo', 'USAID'],
    contact: {
      email: 'info@donboscolilongwe.org',
      phone: '+265 1 726 432',
      address: 'Area 23, P.O. Box 30254, Lilongwe 3, Malawi',
    },
    summary:
      'A top-performing gender-equitable TVET institute in Southern Africa with 48% female enrollment, high employability in IT, renewable energy, and apparel production.',
    featured: false,
  },
  {
    id: 'db-palabek-uganda',
    slug: 'don-bosco-vocational-training-center-palabek',
    name: 'Don Bosco VTC Palabek Refugee Settlement',
    shortName: 'DB Palabek Settlement',
    city: 'Lamwo / Palabek',
    countryName: 'Uganda',
    countryCode: 'UG',
    flagEmoji: '🇺🇬',
    provinceCode: 'AGL',
    provinceName: 'Great Lakes',
    tier: 'Tier 2 - Regional Hub',
    overallScore: 85.1,
    rankBand: '#10',
    establishedYear: 2018,
    metrics: {
      employmentRate: 74,
      annualTrainees: 800,
      femaleEnrollmentPct: 52,
      greenTVETRating: 'Gold',
      industryPartnerships: 14,
      workshopQualityScore: 84,
    },
    keyTrades: ['Solar Installation & Repairs', 'Motorcycle Mechanics', 'Building & Concrete Practice', 'Tailoring & Dressmaking', 'Agriculture & Permaculture'],
    tradeIds: ['solar-pv', 'automotive-mechatronics', 'civil-construction', 'agribusiness-food'],
    facilities: [
      'Off-Grid Solar Vocational Rig',
      'Motorcycle & Small Engine Workshop',
      'Regenerative Agro-Forestry Training Plot',
    ],
    accreditationBody: 'Directorate of Industrial Training (DIT, Uganda)',
    leadPartners: ['UNHCR', 'Salesian Missions', 'AICS (Italian Agency for Development Cooperation)'],
    contact: {
      email: 'palabek@salesiansuganda.org',
      phone: '+256 772 450 120',
      address: 'Zone 4, Palabek Refugee Settlement, Lamwo District, Northern Uganda',
    },
    summary:
      'Internationally acclaimed humanitarian TVET center providing certified skills, livelihood tools, and solar empowerment to refugee and host-community youth in northern Uganda.',
    featured: true,
  },
  {
    id: 'db-yaounde-cameroon',
    slug: 'don-bosco-mimboman-yaounde',
    name: 'Collège Don Bosco Mimboman Yaoundé',
    shortName: 'DB Mimboman Yaoundé',
    city: 'Yaoundé',
    countryName: 'Cameroon',
    countryCode: 'CM',
    flagEmoji: '🇨🇲',
    provinceCode: 'ATE',
    provinceName: 'Tropical Equatorial Africa',
    tier: 'Tier 2 - Regional Hub',
    overallScore: 83.2,
    rankBand: '#11',
    establishedYear: 1994,
    metrics: {
      employmentRate: 75,
      annualTrainees: 690,
      femaleEnrollmentPct: 35,
      greenTVETRating: 'Silver',
      industryPartnerships: 16,
      workshopQualityScore: 83,
    },
    keyTrades: ['Industrial Electricity', 'Automotive Repair', 'Woodworking & Cabinetry', 'Metal Fabrication', 'Secretarial Bureau'],
    tradeIds: ['electrical-installation', 'automotive-mechatronics', 'modern-woodworking'],
    facilities: ['Industrial Cabinetry Wood Mill', 'Engine Diagnostics Bay', 'Domestic Wiring Simulator'],
    accreditationBody: 'Ministère de l’Emploi et de la Formation Professionnelle (MINEFOP, Cameroun)',
    leadPartners: ['Don Bosco Mondo', 'French Development Agency (AFD)'],
    contact: {
      email: 'yaounde@salesiens-ate.org',
      phone: '+237 222 22 41 85',
      address: 'Quartier Mimboman, BP 1366, Yaoundé, Cameroun',
    },
    summary:
      'Premier Technical training center serving the central region of Cameroon, equipping youth with certified electro-mechanical and woodworking qualifications.',
    featured: false,
  },
  {
    id: 'db-maputo-mozambique',
    slug: 'instituto-tecnico-dom-bosco-matola-maputo',
    name: 'Instituto Técnico Dom Bosco Matola',
    shortName: 'IT Dom Bosco Matola',
    city: 'Matola / Maputo',
    countryName: 'Mozambique',
    countryCode: 'MZ',
    flagEmoji: '🇲🇿',
    provinceCode: 'MOZ',
    provinceName: 'Mozambique',
    tier: 'Tier 1 - Center of Excellence',
    overallScore: 86.8,
    rankBand: '#12',
    establishedYear: 1997,
    metrics: {
      employmentRate: 83,
      annualTrainees: 890,
      femaleEnrollmentPct: 38,
      greenTVETRating: 'Silver',
      industryPartnerships: 28,
      workshopQualityScore: 88,
    },
    keyTrades: ['Industrial Electrical Maintenance', 'Automotive Engineering', 'Welding & Metal Structures', 'Computer Systems & IT', 'Civil Construction'],
    tradeIds: ['electrical-installation', 'automotive-mechatronics', 'welding-fabrication', 'ict-software'],
    facilities: [
      'Mozal-Supported Industrial Electrical Workshop',
      'Heavy Metal Arc & Argon Welding Center',
      'IT Networking and Cisco Laboratory',
    ],
    accreditationBody: 'ANEP (Autoridade Nacional de Educação Profissional, Moçambique)',
    leadPartners: ['Mozal Aluminium', 'Salesian Missions', 'Swiss Development Cooperation (SDC)'],
    contact: {
      email: 'secretaria@salesianos.org.mz',
      phone: '+258 21 720 445',
      address: 'Av. das Indústrias, Matola, Província de Maputo, Moçambique',
    },
    summary:
      'High-tier Lusophone technical institute closely connected to Mozambique industrial belt, graduating sought-after electricians, welders, and mechatronic specialists.',
    featured: false,
  },
];
