import { KnowledgeResource } from './types';

export const knowledgeResources: KnowledgeResource[] = [
  {
    id: 'tvet-continental-strategy-domestication-report',
    slug: 'tvet-continental-strategy-domestication-report',
    title: 'Accelerating the Domestication of the Continental TVET Strategy (2025–2034)',
    type: 'Policy Brief',
    topic: 'Continental TVET Policy',
    category: 'Policy & Advocacy',
    year: 2026,
    publishDate: '2026-08-15',
    authors: ['DBTA Policy Directorate'],
    authorOrIssuer: 'Don Bosco Tech Africa Policy Directorate',
    programme: 'Advocacy & Policy',
    abstract: 'Strategic policy synthesis analyzing practical pathways for TVET institutions and national qualification frameworks to domesticate the African Union Continental TVET Strategy 2025–2034.',
    description: 'Strategic policy synthesis analyzing practical pathways for TVET institutions and national qualification frameworks to domesticate the African Union Continental TVET Strategy 2025–2034.',
    fileFormat: 'PDF',
    format: 'PDF',
    fileSize: '3.8 MB',
    fileSizeBytes: '3.8 MB',
    downloadUrl: 'https://dbtechafrica.org/wp-content/uploads/2026/08/coverasa2026.png',
    featuredImage: 'https://dbtechafrica.org/wp-content/uploads/2026/08/coverasa2026.png',
    tags: ['Policy', 'African Union', 'Qualification Frameworks', 'Strategic Plan'],
  },
  {
    id: 'rpl-framework-implementation-manual',
    slug: 'rpl-framework-implementation-manual',
    title: 'Recognition of Prior Learning (RPL): Practitioner Implementation Guide for African TVET',
    type: 'Toolkit',
    topic: 'Recognition of Prior Learning',
    category: 'Curriculum & Toolkits',
    year: 2026,
    publishDate: '2026-03-20',
    authors: ['DBTA & TEVETA Technical Working Group'],
    authorOrIssuer: 'DBTA & TEVETA Technical Working Group',
    country: 'Malawi & Burkina Faso',
    programme: 'RPL Initiative',
    abstract: 'Comprehensive operational manual detailing the diagnostic assessment, portfolio evidence compilation, and moderation protocols for informal sector artisan certification.',
    description: 'Comprehensive operational manual detailing the diagnostic assessment, portfolio evidence compilation, and moderation protocols for informal sector artisan certification.',
    fileFormat: 'PDF',
    format: 'PDF',
    fileSize: '5.2 MB',
    fileSizeBytes: '5.2 MB',
    downloadUrl: 'https://dbtechafrica.org/wp-content/uploads/2026/03/1-18.jpg',
    featuredImage: 'https://dbtechafrica.org/wp-content/uploads/2026/03/1-18.jpg',
    tags: ['RPL', 'Certification', 'Informal Economy', 'Artisan Accreditation'],
  },
  {
    id: 'green-tvet-solar-water-pumping-curriculum',
    slug: 'green-tvet-solar-water-pumping-curriculum',
    title: 'Solar Photovoltaic Water Pumping Systems (SPVWPS) Training Curriculum',
    type: 'Manual',
    topic: 'Renewable Energy & Green TVET',
    category: 'Green TVET & Solar',
    year: 2025,
    publishDate: '2025-11-10',
    authors: ['DBTA & BMZ Green Specialists'],
    authorOrIssuer: 'Don Bosco Tech Africa & BMZ Green Specialists',
    programme: 'Green TVET Project',
    abstract: 'Technical instructional curriculum and practical laboratory exercises for solar technicians on sizing, installing, and servicing off-grid solar water pumping infrastructure.',
    description: 'Technical instructional curriculum and practical laboratory exercises for solar technicians on sizing, installing, and servicing off-grid solar water pumping infrastructure.',
    fileFormat: 'PDF',
    format: 'PDF',
    fileSize: '6.4 MB',
    fileSizeBytes: '6.4 MB',
    downloadUrl: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Hands-On-Technical-Training.png',
    featuredImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Hands-On-Technical-Training.png',
    tags: ['Solar PV', 'Renewable Energy', 'Water Pumping', 'Green TVET'],
  },
  {
    id: 'continental-graduate-tracer-report-2025',
    slug: 'continental-graduate-tracer-report-2025',
    title: 'Continental TVET Graduate Tracer & Labor Market Integration Report',
    type: 'Report',
    topic: 'Youth Employment & Labor Market',
    category: 'Research & Tracer Studies',
    year: 2025,
    publishDate: '2025-09-18',
    authors: ['DBTA Inserjeune Research Unit'],
    authorOrIssuer: 'DBTA Inserjeune Research Unit',
    programme: 'Inserjeune Ecosystem',
    abstract: 'Empirical analytics derived from 119 Salesian TVET centres evaluating graduate employment rates, salary benchmarks, and employer satisfaction across 35 African countries.',
    description: 'Empirical analytics derived from 119 Salesian TVET centres evaluating graduate employment rates, salary benchmarks, and employer satisfaction across 35 African countries.',
    fileFormat: 'PDF',
    format: 'PDF',
    fileSize: '4.6 MB',
    fileSizeBytes: '4.6 MB',
    downloadUrl: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Empowering-Youth.png',
    featuredImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Empowering-Youth.png',
    tags: ['Tracer Studies', 'Inserjeune', 'Employment', 'Labor Market Intelligence'],
  },
  {
    id: 'qms-tvet-quality-assurance-handbook',
    slug: 'qms-tvet-quality-assurance-handbook',
    title: 'Quality Management System (QMS) Handbook for Salesian TVET Institutions',
    type: 'Toolkit',
    topic: 'Institutional Governance & Quality',
    category: 'Institutional Governance',
    year: 2024,
    publishDate: '2024-06-25',
    authors: ['DBTA Quality Assurance Directorate'],
    authorOrIssuer: 'DBTA Quality Assurance Directorate',
    programme: 'Quality TVET',
    abstract: 'Standardized operating procedures, institutional governance audits, workshop safety guidelines, and pedagogical benchmarks for TVET centre directors.',
    description: 'Standardized operating procedures, institutional governance audits, workshop safety guidelines, and pedagogical benchmarks for TVET centre directors.',
    fileFormat: 'PDF',
    format: 'PDF',
    fileSize: '4.1 MB',
    fileSizeBytes: '4.1 MB',
    downloadUrl: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Quality-Education-Innovation.png',
    featuredImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Quality-Education-Innovation.png',
    tags: ['Quality Assurance', 'QMS', 'Governance', 'Standard Operating Procedures'],
  },
  {
    id: 'climate-smart-agribusiness-training-framework',
    slug: 'climate-smart-agribusiness-training-framework',
    title: 'Climate-Smart Agribusiness: Four-Pillar Training Framework for Youth',
    type: 'Research Paper',
    topic: 'Agriculture & Food Security',
    category: 'Modern Agriculture',
    year: 2024,
    publishDate: '2024-04-12',
    authors: ['DBTA & CultivAid Agronomy Taskforce'],
    authorOrIssuer: 'DBTA & CultivAid Agronomy Taskforce',
    programme: 'Agriculture for Life',
    abstract: 'Action research examining the pilot integration of precision weather sensors, solar drip systems, and market linkages across Salesian agricultural demonstration farms in Kenya and Madagascar.',
    description: 'Action research examining the pilot integration of precision weather sensors, solar drip systems, and market linkages across Salesian agricultural demonstration farms in Kenya and Madagascar.',
    fileFormat: 'PDF',
    format: 'PDF',
    fileSize: '3.2 MB',
    fileSizeBytes: '3.2 MB',
    downloadUrl: 'https://dbtechafrica.org/wp-content/uploads/2026/01/IMG_2709-1.jpg',
    featuredImage: 'https://dbtechafrica.org/wp-content/uploads/2026/01/IMG_2709-1.jpg',
    tags: ['Agriculture', 'Greenhouse', 'Hydroponics', 'Food Security'],
  },
  {
    id: 'dbta-strategic-plan-2023-2028',
    slug: 'dbta-strategic-plan-2023-2028',
    title: 'Don Bosco Tech Africa Strategic Plan (2023–2028): Transforming Continental TVET',
    type: 'Strategic Plan',
    topic: 'Institutional Strategy',
    category: 'Policy & Advocacy',
    year: 2023,
    publishDate: '2023-01-15',
    authors: ['DBTA Board of Directors'],
    authorOrIssuer: 'DBTA Board of Directors',
    programme: 'Governance & Strategy',
    abstract: 'The 5-year strategic blueprint outlining DBTA’s priorities in green transition, digital acceleration, sustainable financing, and youth employment across 35 African nations.',
    description: 'The 5-year strategic blueprint outlining DBTA’s priorities in green transition, digital acceleration, sustainable financing, and youth employment across 35 African nations.',
    fileFormat: 'PDF',
    format: 'PDF',
    fileSize: '7.1 MB',
    fileSizeBytes: '7.1 MB',
    downloadUrl: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Pan-African-Network.png',
    featuredImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Pan-African-Network.png',
    tags: ['Strategy', 'Strategic Plan', 'Pan-African', 'Five Year Blueprint'],
  },
];

export const knowledgeItems = knowledgeResources;
