import { NewsArticle } from './types';

export const newsArticles: NewsArticle[] = [
  {
    id: 'conference-continental-tvet-strategy-2025-2034',
    slug: 'conference-on-accelerating-the-domestication-of-the-continental-tvet-strategy-2025-2034',
    title: 'Conference on Accelerating the Domestication of the Continental TVET Strategy (2025–2034)',
    excerpt: 'Don Bosco Tech Africa convenes continental policymakers, development partners, and TVET leaders to align technical training institutions with the African Union’s decade roadmap.',
    content: [
      'Nairobi, Kenya — Don Bosco Tech Africa (DBTA) successfully hosted a landmark conference bringing together educational authorities, international development partners, and TVET directors to accelerate the domestication of the African Union Continental TVET Strategy (2025–2034).',
      'The assembly focused on actionable mechanisms to transition national vocational curricula from theoretical models to competency-based, industry-aligned apprenticeships.',
      'Key dialogue tracks addressed the greening of TVET campuses, digital infrastructure investments, cross-border qualification recognition, and public-private financing models to expand access for marginalized youth.',
      'Delegates emphasized that the 119 Salesian TVET institutions spread across 35 African countries provide an operational prototype for delivering decentralized, community-rooted technical excellence at continental scale.',
    ],
    category: 'Conference',
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/08/coverasa2026.png',
    publishedDate: '2026-08-26',
    author: 'DBTA Communications',
    location: 'Nairobi, Kenya',
    readTimeMinutes: 5,
    tags: ['Continental TVET Strategy', 'African Union', 'Policy Advocacy', 'ASA 2026'],
  },
  {
    id: 'from-commitment-to-practice-african-tvet',
    slug: 'from-commitment-to-practice-deepening-inclusivity-sustainability-and-skills-recognition-in-african-tvet',
    title: 'From Commitment to Practice: Deepening Inclusivity, Sustainability and Skills Recognition in African TVET',
    excerpt: 'The Online Annual Stakeholders Assembly (ASA 2026) outlines pragmatic milestones for expanding green technology courses and gender parity across the Salesian network.',
    content: [
      'The Annual Stakeholders Assembly convened virtually, uniting over 300 delegates from across 15 Salesian Provinces in Africa and Madagascar.',
      'Under the theme "From Commitment to Practice," the assembly reviewed progress on the continental Green TVET initiative, the rollout of Solar Photovoltaic Water Pumping Systems (SPVWPS), and the expansion of the Inserjeune tracer platform.',
      'Provincial coordinators presented evidence demonstrating a notable increase in female enrollment in traditionally male-dominated trades such as electrical installation, automotive technology, and solar engineering.',
      'Strategic partner representatives from Porticus, BMZ, and Jugend Eine Welt commended DBTA for its institutional transparency and rigorous monitoring frameworks.',
    ],
    category: 'Assembly',
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/03/Screenshot-60-1.png',
    publishedDate: '2026-03-27',
    author: 'DBTA Media Directorate',
    location: 'Continental Secretariat (Virtual Assembly)',
    readTimeMinutes: 4,
    tags: ['Annual Stakeholders Assembly', 'Inclusivity', 'Green TVET', 'Youth Employability'],
  },
  {
    id: 'malawi-burkina-faso-advance-rpl-frameworks',
    slug: 'malawi-and-burkina-faso-advance-recognition-of-prior-learning-frameworks',
    title: 'Malawi and Burkina Faso Advance Recognition of Prior Learning (RPL) Frameworks',
    excerpt: 'Salesian TVET centres in Lilongwe and Ouagadougou complete pilot assessments certifying over 450 informal sector craftspeople and artisans.',
    content: [
      'In a major milestone for informal economy empowerment, Don Bosco Tech Africa in collaboration with TEVETA Malawi and the National TVET Commission in Burkina Faso successfully completed diagnostic skills assessments for 450 master craftspeople.',
      'The Recognition of Prior Learning (RPL) framework evaluates competencies acquired through years of informal workshop experience, validating artisan skills against national occupational standards.',
      'Graduates received government-recognized trade certificates in masonry, welding, automotive mechanics, and electrical wiring, enabling them to formalize their businesses and access formal procurement opportunities.',
      'DBTA plans to scale the RPL methodology to six additional countries across East and West Africa over the next two years.',
    ],
    category: 'Training',
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/03/1-18.jpg',
    publishedDate: '2026-03-27',
    author: 'DBTA Project Office',
    location: 'Lilongwe & Ouagadougou',
    readTimeMinutes: 4,
    tags: ['Recognition of Prior Learning', 'RPL', 'Malawi', 'Burkina Faso', 'Artisan Certification'],
  },
  {
    id: 'agriculture-for-life-project-embu',
    slug: 'agriculture-for-life-project',
    title: 'Agriculture for Life: Climate-Smart Agribusiness Consultative Session at Don Bosco Embu',
    excerpt: 'Agronomists, vocational instructors, and youth leaders evaluate precision agriculture, solar irrigation, and food value chains in Kenya.',
    content: [
      'Embu, Kenya — Technical teams from Don Bosco Tech Africa, CultivAid, and the Salesian Province of Eastern Africa (AFE) gathered at Don Bosco Vocational Training Centre Embu to evaluate ongoing installations under the "Agriculture for Life" project.',
      'The pilot project introduces precision weather monitoring stations, automated solar-powered drip irrigation, and high-value horticultural greenhouses.',
      'The initiative demonstrates how vocational agricultural education can be repositioned as an attractive, technology-driven entrepreneurship pathway for African youth.',
      'Produce from the demonstration farm contributes directly to institutional food self-sufficiency while training students in commercial farm management and supply chain logistics.',
    ],
    category: 'Green TVET',
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/01/IMG_2709-1.jpg',
    publishedDate: '2026-01-26',
    author: 'DBTA Agriculture Desk',
    location: 'Embu, Kenya',
    readTimeMinutes: 4,
    tags: ['Agriculture for Life', 'Climate-Smart Agribusiness', 'Don Bosco Embu', 'Kenya'],
  },
];
