import { Project } from './types';

export const projects: Project[] = [
  {
    id: 'green-tvet-renewable-energy',
    slug: 'green-tvet-renewable-energy',
    title: 'Green TVET & Solar Energy Project',
    tagline: 'Empowering youth with certified solar and renewable energy skills across Africa',
    thematicArea: 'Green TVET',
    status: 'Multi-Year Flagship',
    leadPartner: 'BMZ (German Federal Ministry for Economic Cooperation and Development)',
    partners: ['Jugend Eine Welt (J1W)', 'Don Bosco Green Alliance', 'Schneider Electric', 'EVBB'],
    targetCountries: ['Kenya', 'Tanzania', 'Uganda', 'Rwanda', 'Ghana', 'Nigeria', 'Madagascar', 'Burkina Faso'],
    targetCentresCount: 28,
    beneficiariesTarget: '6,000+ Young Men and Women',
    summary: 'The Green TVET Project fosters environmental conservation and green transition within Salesian TVET institutions across Africa. It equips centres with cutting-edge Solar PV training benches, establishes certified curricula for Solar Water Pumping (SPVWPS), trains Master Trainers, and builds industry partnerships for renewable energy job placements.',
    objectives: [
      'Equip 28 Salesian TVET centres with modern Solar PV and clean energy training equipment',
      'Train and certify 120+ Green TVET Master Trainers and solar instructors',
      'Provide accredited renewable energy vocational qualifications to 6,000+ youth',
      'Establish solar entrepreneurship incubators and business links for graduates',
    ],
    keyActivities: [
      'Procurement and installation of specialized Solar PV testing benches and rooftop arrays',
      'Regional Master Trainer pedagogical workshops in Nairobi and Accra',
      'Development of harmonized Solar PV Water Pumping Systems (SPVWPS) course manuals',
      'Campus-wide energy audits and transition to solar power in partner institutes',
    ],
    expectedOutcomes: [
      '80%+ of graduated solar technicians placed in clean energy enterprises or self-employment',
      'Adoption of green campus policies and renewable power across Salesian TVET institutions',
      'Increased female participation in electrical and renewable energy trades to over 35%',
    ],
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Hands-On-Technical-Training.png',
    publishedDate: '2023-01-15',
  },
  {
    id: 'agriculture-for-life',
    slug: 'agriculture-for-life',
    title: 'Agriculture for Life Project',
    tagline: 'Modernizing agro-pastoral training and climate-smart agribusiness in Salesian centres',
    thematicArea: 'Agriculture',
    status: 'Active',
    leadPartner: 'Porticus & Salesians of Don Bosco',
    partners: ['CultivAid', 'Worlddidac', 'Ministry of Agriculture Kenya'],
    targetCountries: ['Kenya', 'Tanzania', 'Madagascar', 'Uganda', 'Rwanda'],
    targetCentresCount: 12,
    beneficiariesTarget: '3,200+ Agricultural Trainees',
    summary: 'The Agriculture for Life Project transforms agricultural vocational training across four strategic pillars: Education/Training, Agricultural Production, Pastoral/Social Impact, and Sustainability through Agribusiness. Centred around pilots like Don Bosco Embu and Don Bosco Makuyu, it integrates climate-smart weather monitoring, drip irrigation, greenhouse horticulture, and post-harvest value addition.',
    objectives: [
      'Upgrade agricultural training facilities with climate-smart drip irrigation and automated weather stations',
      'Revitalize institutional orchards, crop production units, and animal husbandry sectors',
      'Develop modern agribusiness curricula that position farming as a lucrative, tech-driven career for youth',
      'Create rural farm-to-market cooperatives for Salesian TVET graduates',
    ],
    keyActivities: [
      'Site assessments and installation of automated agrometeorological weather stations (e.g. at Don Bosco Embu)',
      'Establishment of climate-resilient crop demonstration plots and solar-powered boreholes',
      'Hands-on training in organic horticulture, soil conservation, and post-harvest management',
      'Mentorship sessions pairing young trainees with commercial agronomists and export aggregators',
    ],
    expectedOutcomes: [
      'Demonstrated 40% increase in crop yield across project demonstration farms',
      'Graduation of 3,200 youth with certified diplomas in climate-smart agribusiness',
      'Self-sustaining institutional food production reducing TVET boarding costs',
    ],
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/01/IMG_2709-1.jpg',
    publishedDate: '2024-02-10',
  },
  {
    id: 'recognition-of-prior-learning-rpl',
    slug: 'recognition-of-prior-learning-rpl',
    title: 'Recognition of Prior Learning (RPL) Initiative',
    tagline: 'Validating informal skills and transforming artisan livelihoods into certified careers',
    thematicArea: 'Recognition of Prior Learning',
    status: 'Active',
    leadPartner: 'Don Bosco Mondo / Jugend Dritte Welt',
    partners: ['TEVETA Malawi', 'National TVET Commission Burkina Faso', 'National Qualification Authorities'],
    targetCountries: ['Malawi', 'Burkina Faso', 'Kenya', 'Rwanda'],
    targetCentresCount: 16,
    beneficiariesTarget: '4,500+ Informal Artisans & Youths',
    summary: 'The RPL Initiative addresses a critical systemic barrier in African labor markets: informal artisans possessing mastery in trades such as masonry, metal welding, carpentry, and electrical wiring but lacking paper credentials. Working alongside national TEVET regulators, DBTA establishes assessment centers, develops portfolio tools, and provides targeted bridge training to certify thousands of informal craftspeople.',
    objectives: [
      'Develop harmonized RPL assessment toolkits and assessor training manuals in partnership with national bodies',
      'Accredit 16 Salesian TVET institutions as official national RPL assessment hubs',
      'Assess and award formal government-recognized qualification certificates to 4,500 artisans',
      'Advocate for fair wage structures and public procurement access for RPL-certified craftspeople',
    ],
    keyActivities: [
      'Capacity building workshops for RPL assessors and moderators in Lilongwe and Ouagadougou',
      'Community outreach campaigns targeting informal jua kali clusters, workshops, and artisan associations',
      'Conducting diagnostic practical skill assessments and providing modular gap-filling short courses',
      'Official graduation ceremonies issuing accredited national vocational certificates',
    ],
    expectedOutcomes: [
      'Documented average 35% increase in monthly earnings for certified RPL artisans',
      'Formal eligibility of certified artisans to bid for municipal and public infrastructure contracts',
      'Enhanced institutional trust between national regulatory boards and the Salesian TVET network',
    ],
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/03/1-18.jpg',
    publishedDate: '2024-06-15',
  },
  {
    id: 'inserjeune-job-placement-system',
    slug: 'inserjeune-job-placement-system',
    title: 'Inserjeune Job Placement & Tracer Ecosystem',
    tagline: 'Institutionalizing school-to-work transition across 119 TVET centres',
    thematicArea: 'Employability & Job Placement',
    status: 'Multi-Year Flagship',
    leadPartner: 'Porticus & Salesians of Don Bosco',
    partners: ['Federation of African Employers', 'Chambers of Commerce', 'Local Industry Associations'],
    targetCountries: ['Pan-African (All 35 Countries)'],
    targetCentresCount: 119,
    beneficiariesTarget: '45,000+ Enrolled Students & Alumni',
    summary: 'The Inserjeune system is DBTA’s proprietary continental job placement and graduate tracking platform. Supported by trained Job Service Officers (JSOs) stationed in each centre, the platform captures real-time data on student industrial attachments, alumni employment trajectories, employer satisfaction indices, and labor market skill shortages.',
    objectives: [
      'Maintain operational Job Service Offices in all 119 Don Bosco TVET centres',
      'Track 100% of graduating cohorts longitudinally over 6, 12, and 24 months post-graduation',
      'Foster formal Memoranda of Understanding (MoUs) with industrial employers in every Salesian province',
      'Feed labor market analytics directly into annual curriculum revision cycles',
    ],
    keyActivities: [
      'Continuous training of Provincial Job Service Officers (JSOs) in career guidance and employer networking',
      'Deployment of the upgraded digital Inserjeune Tracer web application across all provinces',
      'Hosting regional Career Fairs, Industry Roundtables, and Graduate Employer Matchmaking days',
      'Publication of the annual Continental Graduate Employment & Tracer Report',
    ],
    expectedOutcomes: [
      'Consistent continental job placement rate exceeding 57%',
      'Active database of over 1,500 vetted corporate recruitment partners across Africa',
      'Direct feedback loop aligning technical workshop syllabi with contemporary employer needs',
    ],
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Empowering-Youth.png',
    publishedDate: '2023-08-01',
  },
  {
    id: 'saam-africa-europe-tvet-mobility',
    slug: 'saam-africa-europe-tvet-mobility',
    title: 'SAAM: Sectoral Adaptation Action Model for TVET',
    tagline: 'Fostering peer exchange and pedagogical mobility between African and European TVET educators',
    thematicArea: 'Capacity Building',
    status: 'Completed',
    leadPartner: 'European Union & EVBB',
    partners: ['SAAM Consortium', 'Jugend Eine Welt', 'Worlddidac', 'Mondo'],
    targetCountries: ['Kenya', 'Nigeria', 'Cameroon', 'Chad', 'Spain', 'Italy', 'Belgium'],
    targetCentresCount: 15,
    beneficiariesTarget: '350+ TVET Staff & Young Exchange Trainees',
    summary: 'An ambitious intercontinental partnership bridging technical vocational education between Africa and the European Union. SAAM facilitated high-level technical study tours, instructor exchanges, and joint curriculum development in automotive engineering, renewable energy, and ICT.',
    objectives: [
      'Promote cross-continental mobility and knowledge sharing between European and African TVET institutions',
      'Benchmark African technical training methodologies against European dual-apprenticeship frameworks',
      'Strengthen international pedagogical networks and cooperative training consortiums',
    ],
    keyActivities: [
      'Instructor exchange residencies in Spain, Italy, and Belgium for African Salesian trainers',
      'Joint technical workshops on digital diagnostics and hybrid automotive mechanics',
      'Publication of cross-regional TVET policy recommendations for intercontinental mobility',
    ],
    expectedOutcomes: [
      'Institutional adoption of modular competency-based testing frameworks in partner centres',
      'Long-term bilateral twinning arrangements between African and European vocational colleges',
    ],
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Quality-Education-Innovation.png',
    publishedDate: '2022-09-01',
  },
];
