import { Province } from './types';

export const provinces: Province[] = [
  {
    code: 'AFE',
    name: 'Eastern Africa',
    fullName: 'Salesian Province of Saint John Bosco (Eastern Africa)',
    coordinatorName: 'Br. Benedict Muriuki',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/brBenedict.png',
    countries: ['Kenya', 'Tanzania', 'Sudan', 'South Sudan'],
    centreCount: 18,
    headquarters: 'Nairobi, Kenya',
    description: 'Coordinating high-impact TVET centres across Kenya, Tanzania, and Sudan regions with strong solar and digital skills integration.',
  },
  {
    code: 'AFC',
    name: 'Central Africa',
    fullName: 'Salesian Province of Central Africa',
    coordinatorName: 'Fr. Marc Abumba',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/Marc-Abumba-1.jpg',
    countries: ['Democratic Republic of the Congo', 'Republic of the Congo'],
    centreCount: 14,
    headquarters: 'Lubumbashi, DRC',
    description: 'Focusing on heavy industrial trades, mechanical engineering, electrical installations, and youth empowerment in Central Africa.',
  },
  {
    code: 'AGL',
    name: 'Great Lakes',
    fullName: 'Salesian Province of the Great Lakes (Africa Great Lakes)',
    coordinatorName: 'Fr. Callixte Ukwitegetse',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/Fr.-Calixte-1.jpg',
    countries: ['Rwanda', 'Burundi', 'Uganda'],
    centreCount: 11,
    headquarters: 'Kigali, Rwanda',
    description: 'Exemplary hub for ICT, hospitality, carpentry, and modern construction with strong government TVET alignment.',
  },
  {
    code: 'AOS',
    name: 'West Africa South',
    fullName: 'Salesian Province of West Africa South',
    coordinatorName: 'Fr. Mark K. Eshun',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/FrmarkAshun.jpg',
    countries: ['Ghana', 'Nigeria', 'Liberia', 'Sierra Leone'],
    centreCount: 12,
    headquarters: 'Accra, Ghana',
    description: 'Empowering West African youth in industrial automation, renewable energy, and automotive technology.',
  },
  {
    code: 'AON',
    name: 'West Africa North',
    fullName: 'Salesian Province of West Africa North',
    coordinatorName: 'Fr. Franck Ametepe',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/Fr-frank.jpeg',
    countries: ['Senegal', 'Mali', 'Guinea', 'Burkina Faso', "Cote d'Ivoire", 'Togo', 'Benin'],
    centreCount: 15,
    headquarters: 'Lomé, Togo',
    description: 'Spearheading Recognition of Prior Learning (RPL), solar PV water pumping systems, and agro-pastoral trades across Francophone West Africa.',
  },
  {
    code: 'ZMB',
    name: 'Zambia / Zimbabwe / Malawi / Namibia',
    fullName: 'Salesian Vice-Province of ZMB',
    coordinatorName: 'Fr. John Musonda',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/FrJohnZMB2.jpeg',
    countries: ['Zambia', 'Zimbabwe', 'Malawi', 'Namibia'],
    centreCount: 10,
    headquarters: 'Lusaka, Zambia',
    description: 'Leading in RPL framework implementation, solar entrepreneurship, and rural artisan certification.',
  },
  {
    code: 'MOZ',
    name: 'Mozambique',
    fullName: 'Salesian Vice-Province of Mozambique',
    coordinatorName: 'Fr. Pedro Alexandre Meia',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/PTVT-MOZ.png',
    countries: ['Mozambique'],
    centreCount: 8,
    headquarters: 'Maputo, Mozambique',
    description: 'Advancing technical trades in masonry, metal fabrication, solar installation, and maritime vocational skills.',
  },
  {
    code: 'MDG',
    name: 'Madagascar & Mauritius',
    fullName: 'Salesian Province of Madagascar',
    coordinatorName: 'Fr. Berthin Solonirina',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/Fr-BethinMDG.jpg',
    countries: ['Madagascar', 'Mauritius'],
    centreCount: 9,
    headquarters: 'Antananarivo, Madagascar',
    description: 'Renowned for agricultural mechanization, textile crafts, electrical engineering, and eco-sustainable trades.',
  },
  {
    code: 'ATE',
    name: 'Equatorial Tropical Africa',
    fullName: 'Salesian Province of Equatorial Tropical Africa',
    coordinatorName: 'Br. David Beyeme',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/david1.jpg',
    countries: ['Cameroon', 'Central African Republic', 'Chad', 'Gabon', 'Equatorial Guinea'],
    centreCount: 8,
    headquarters: 'Yaoundé, Cameroon',
    description: 'Providing vocational lifelines to vulnerable and conflict-affected youths across Central and Equatorial Africa.',
  },
  {
    code: 'ANN',
    name: 'Nigeria North/West',
    fullName: 'Salesian Province of Nigeria',
    coordinatorName: 'Mr. Cletus Linus',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/cletus.png',
    countries: ['Nigeria'],
    centreCount: 6,
    headquarters: 'Lagos, Nigeria',
    description: 'Focusing on digital media, mechatronics, welding technology, and female youth vocational empowerment.',
  },
  {
    code: 'ANG',
    name: 'Angola',
    fullName: 'Salesian Vice-Province of Angola',
    coordinatorName: 'Fr. Kachapilly Jojo',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/Jojo.jpg',
    countries: ['Angola'],
    centreCount: 7,
    headquarters: 'Luanda, Angola',
    description: 'Equipping young Angolans in industrial electricity, plumbing, computing, and automobile maintenance.',
  },
  {
    code: 'AFM',
    name: 'Southern Africa',
    fullName: 'Salesian Province of Southern Africa',
    coordinatorName: 'Mr. Gabriel Hamuy',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/Gabriel.jpeg',
    countries: ['South Africa', 'Lesotho', 'Eswatini'],
    centreCount: 6,
    headquarters: 'Johannesburg, South Africa',
    description: 'Pioneering green energy transitions, advanced tooling, and youth entrepreneurship incubators in Southern Africa.',
  },
  {
    code: 'TZA',
    name: 'Tanzania',
    fullName: 'Salesian Province of Tanzania',
    coordinatorName: 'Mr. Oswald Manyerere',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/manyerere2.jpg',
    countries: ['Tanzania'],
    centreCount: 5,
    headquarters: 'Dar es Salaam, Tanzania',
    description: 'High-performing TVET network with national VETA certification and prominent industrial apprenticeship pipelines.',
  },
  {
    code: 'AET',
    name: 'Ethiopia & Eritrea',
    fullName: 'Salesian Vice-Province of Ethiopia and Eritrea',
    coordinatorName: 'Mr. Mender Alemseged',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/alemseged1.jpg',
    countries: ['Ethiopia', 'Eritrea'],
    centreCount: 8,
    headquarters: 'Addis Ababa, Ethiopia',
    description: 'Delivering technical trades, graphic design, leather crafts, and industrial electronics in the Horn of Africa.',
  },
  {
    code: 'ACC',
    name: 'Congo-Congo Brazzaville',
    fullName: 'Salesian Vice-Province of Congo',
    coordinatorName: 'Fr. Tshibangu Joachim',
    coordinatorTitle: 'Provincial TVET Coordinator',
    coordinatorImage: 'https://dbtechafrica.org/wp-content/uploads/2019/06/joachim.jpg',
    countries: ['Republic of the Congo'],
    centreCount: 4,
    headquarters: 'Brazzaville, Congo',
    description: 'Dedicated to vocational training for vulnerable urban youth, carpentry, and electrical building services.',
  },
];
