import { ImpactStory } from './types';

export const impactStories: ImpactStory[] = [
  {
    id: 'esther-solar-technician-kenya',
    slug: 'esther-solar-technician-kenya',
    title: 'Powering Rural Communities: Esther’s Journey from Trainee to Certified Solar Entrepreneur',
    name: 'Esther Mwangi',
    protagonistName: 'Esther Mwangi',
    role: 'Certified Solar PV Installer & Entrepreneur',
    trade: 'Solar Photovoltaic Technology',
    course: 'Solar PV Systems & Electrical Installation',
    country: 'Kenya',
    year: '2024',
    centre: 'Don Bosco Boys Town Karen',
    challenge: 'Growing up in a rural community with intermittent electricity, Esther faced financial constraints that prevented her from pursuing conventional university tuition. She sought practical technical skills in a field traditionally dominated by male peers.',
    intervention: 'Esther enrolled in the Green TVET Solar PV Program at Don Bosco Boys Town Karen, supported by DBTA and BMZ. She received practical hands-on training on solar testing benches, solar water pumping systems, and entrepreneurship mentorship from the center’s Job Service Office (JSO).',
    outcome: 'Following her graduation with top honors, Esther secured an industrial attachment with a regional off-grid solar enterprise before founding her own solar installation venture. Today, her company has installed clean solar power in over 120 rural households and employs three fellow Don Bosco alumni.',
    quote: 'Don Bosco didn’t just teach me how to connect solar panels—they gave me the confidence, technical rigor, and values to run an ethical business that brings light to my own community.',
    excerpt: 'How Esther mastered solar photovoltaics at Don Bosco Karen and founded a clean-energy enterprise powering 120+ off-grid households in rural Kenya.',
    image: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Hands-On-Technical-Training.png',
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Hands-On-Technical-Training.png',
    fullStory: 'Esther Mwangi’s story exemplifies the transformative potential of modern vocational training in renewable energy. Entering the workshop for the first time, Esther was one of only four women in her class. Through DBTA’s gender inclusion initiatives and continuous mentorship from certified green instructors, she quickly mastered system sizing, inverter wiring, and battery storage diagnostics. Through the support of the Job Service Office (JSO) and the digital Inserjeune tracer platform, Esther was connected with commercial solar distributors in Nairobi, where she honed her field experience before launching "Kilima Solar Solutions". Today, she is an active advocate for young women in technical trades, regularly returning to Don Bosco Karen as a guest speaker to inspire new cohorts of solar apprentices.',
    date: '2026-03-12',
    projectSlug: 'green-tvet-renewable-energy',
  },
  {
    id: 'amadou-rpl-certification-burkina-faso',
    slug: 'amadou-rpl-certification-burkina-faso',
    title: 'From Informal Mason to Licensed Contractor: The Power of Recognition of Prior Learning',
    name: 'Amadou Ouedraogo',
    protagonistName: 'Amadou Ouedraogo',
    role: 'Licensed Master Builder & Mason',
    trade: 'Civil Construction & Masonry',
    course: 'Masonry & Construction Management',
    country: 'Burkina Faso',
    year: '2025',
    centre: 'Centre Professionnel Don Bosco Ouagadougou',
    challenge: 'Amadou worked as an informal mason for twelve years across Ouagadougou. Despite mastering complex structural bricklaying, he was consistently locked out of municipal government tenders and high-paying contracts because he lacked a formal government diploma.',
    intervention: 'Through DBTA’s Recognition of Prior Learning (RPL) initiative at Centre Professionnel Don Bosco Ouagadougou, Amadou’s existing practical competencies were systematically assessed by accredited national examiners, followed by a 3-week modular bridge course covering blueprint reading and occupational safety.',
    outcome: 'Amadou received his official State-Recognized TVET Qualification Certificate. Armed with formal accreditation, he registered his construction enterprise and recently won a public school refurbishment contract, increasing his business revenues by 200%.',
    quote: 'For twelve years I built beautiful houses, but on paper I had no identity as a professional. Don Bosco Tech Africa and RPL validated my life’s work and opened doors I never thought possible.',
    excerpt: 'After twelve years in the informal construction sector, Amadou earned his official state TVET certification through DBTA’s RPL initiative, unlocking public municipal tenders.',
    image: 'https://dbtechafrica.org/wp-content/uploads/2026/03/1-18.jpg',
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/03/1-18.jpg',
    fullStory: 'The informal economy in West Africa sustains millions of skilled craftspeople whose talents remain invisible to formal financing and public procurement. When Don Bosco Tech Africa launched the RPL pilot in Ouagadougou with the national qualification authority, Amadou was among the first master artisans to undergo diagnostic assessment. The assessment demonstrated that his practical masonry skills exceeded standard benchmark levels. By completing the targeted theoretical modules in structural mathematics and architectural drafting at the Don Bosco center, he fulfilled all criteria for formal state certification. Amadou has now enrolled four of his own apprentices into the Don Bosco vocational program, creating a generational legacy of accredited technical excellence.',
    date: '2026-02-18',
    projectSlug: 'recognition-of-prior-learning-rpl',
  },
  {
    id: 'samuel-climate-smart-agriculture-kenya',
    slug: 'samuel-climate-smart-agriculture-kenya',
    title: 'Farming with Technology: Samuel Champions Climate-Smart Horticulture in Embu',
    name: 'Samuel Ndung’u',
    protagonistName: 'Samuel Ndung’u',
    role: 'Agribusiness Entrepreneur & Greenhouse Specialist',
    trade: 'Climate-Smart Agriculture & Agribusiness',
    course: 'Greenhouse Horticulture & Precision Irrigation',
    country: 'Kenya',
    year: '2024',
    centre: 'Don Bosco Vocational Training Centre Embu',
    challenge: 'Faced with prolonged drought cycles and fluctuating market prices for traditional subsistence crops, Samuel sought innovative agricultural techniques that could generate sustainable income on limited acreage.',
    intervention: 'Samuel enrolled in the "Agriculture for Life" program at Don Bosco Embu, where he trained on automated agrometeorological weather stations, solar-powered drip irrigation, greenhouse vegetable production, and value addition.',
    outcome: 'Samuel transformed his family’s two-acre farm into a high-yielding, climate-resilient organic capsicum and tomato enterprise. By applying moisture sensors and solar drip networks mastered at Don Bosco, he reduced water consumption by 50% while achieving year-round harvesting.',
    quote: 'Modern farming is not about back-breaking labor—it is about data, clean energy, and market timing. Don Bosco taught us that agriculture is one of Africa’s greatest frontiers for young entrepreneurs.',
    excerpt: 'Combining weather sensors and solar drip irrigation learned at Don Bosco Embu, Samuel turned two acres into a thriving organic agribusiness enterprise.',
    image: 'https://dbtechafrica.org/wp-content/uploads/2026/01/IMG_2709-1.jpg',
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/01/IMG_2709-1.jpg',
    fullStory: 'The Agriculture for Life project at Don Bosco Embu aims to change youth perception of agriculture from an activity of last resort into a profitable, technologically advanced industry. Samuel’s training integrated climate-smart demonstration plots with business planning. Under the mentorship of Don Bosco agronomists, he created a direct supply contract with regional hospitality establishments. His enterprise now serves as a local peer demonstration site where surrounding farmers learn climate adaptation techniques.',
    date: '2026-01-20',
    projectSlug: 'agriculture-for-life',
  },
  {
    id: 'clarisse-hospitality-rwanda',
    slug: 'clarisse-hospitality-rwanda',
    title: 'Elevating Rwandan Hospitality: Clarisse’s Ascent in the Culinary Industry',
    name: 'Clarisse Mukamana',
    protagonistName: 'Clarisse Mukamana',
    role: 'Head Pastry Chef & Culinary Instructor',
    trade: 'Hospitality & Culinary Arts',
    course: 'Culinary Arts & Food Production',
    country: 'Rwanda',
    year: '2023',
    centre: 'Don Bosco TVET School Gatenga',
    challenge: 'Clarisse was seeking a vocational pathway that would allow her to gain immediate, accredited employment in Kigali’s rapidly expanding tourism and hospitality sector.',
    intervention: 'She completed the rigorous 2-year Hospitality and Culinary Arts curriculum at Don Bosco Gatenga. Through the centre’s Job Service Office (JSO), she was matched with a leading 5-star hotel in Kigali for an intensive 6-month industrial internship.',
    outcome: 'Her exceptional culinary technique and professional discipline earned her a full-time position as Demi Chef de Partie immediately upon graduation. Within three years, she rose to Head Pastry Chef and now serves as an external industry assessor for TVET examinations in Rwanda.',
    quote: 'The Salesian educational environment gave me not only high culinary standards but the moral grounding and work ethic that every top employer looks for.',
    excerpt: 'From hands-on culinary workshops at Don Bosco Gatenga to Head Pastry Chef at a 5-star Kigali hotel and national TVET assessor.',
    image: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Pan-African-Network.png',
    coverImage: 'https://dbtechafrica.org/wp-content/uploads/2026/04/Pan-African-Network.png',
    fullStory: 'Don Bosco TVET School Gatenga has earned a reputation as one of East Africa’s premier vocational academies for the hospitality sector. Clarisse’s journey reflects the efficacy of DBTA’s dual-training model, where classroom theory is harmonized with continuous industry exposure. Her success has inspired dozens of young women in her community to enroll in culinary arts and tourism trades.',
    date: '2025-11-14',
    projectSlug: 'inserjeune-job-placement-system',
  },
];

export const stories = impactStories;
