import { ThematicArea } from './types';

export const thematicAreas: ThematicArea[] = [
  {
    id: 'quality-tvet',
    slug: 'quality-tvet',
    title: 'Quality TVET & Modernization',
    tagline: 'Standardising Continental TVET Excellence',
    shortDesc: 'Upgrading institutional infrastructure, standardizing curricula, and implementing Quality Management Systems (QMS) across all 119 centres.',
    description: 'Upgrading institutional infrastructure, standardizing curricula, and implementing Quality Management Systems (QMS) across all 119 centres.',
    fullDesc: 'Don Bosco Tech Africa establishes benchmarks for technical excellence across Africa and Madagascar. By deploying the continental QMS framework, modernizing workshop machinery, and aligning trade courses with international industry standards, DBTA ensures that young people receive accredited, high-calibre training that is directly recognized by employers.',
    icon: 'Building2',
    keyPillars: [
      'Continental Quality Management System (QMS)',
      'Modern workshop equipment & tooling upgrades',
      'Dual TVET training models with industry',
      'Standardized curricula across English, French & Portuguese zones',
    ],
    objectives: [
      'Continental Quality Management System (QMS) accreditation across all 119 centres',
      'Modern workshop equipment, industrial tools, and digital simulators in trade labs',
      'Dual TVET training models bridging classroom theory with real-world shop floor practice',
      'Standardized curricula harmonized across English, French, and Portuguese regions',
    ],
    keyMetrics: [
      { value: '119', label: 'TVET Centres', description: 'Under standardized QMS quality audits' },
      { value: '30+', label: 'Modernized Trades', description: 'Curricula harmonized to industry needs' },
      { value: '88%', label: 'Employer Satisfaction', description: 'Rating DBTA graduates work-readiness' },
    ],
    impactMetric: '119 Centres',
    impactLabel: 'Standardized & Accredited',
  },
  {
    id: 'employability-jso',
    slug: 'employability-jso',
    title: 'Employability & Job Placement',
    tagline: 'Connecting Skilled Youth to Dignifying Employment',
    shortDesc: 'Operating dedicated Job Service Offices (JSOs) and the Inserjeune tracer system to connect graduates with dignifying employment and entrepreneurship.',
    description: 'Operating dedicated Job Service Offices (JSOs) and the Inserjeune tracer system to connect graduates with dignifying employment and entrepreneurship.',
    fullDesc: 'Training without employment pathways is incomplete. DBTA establishes Job Service Offices (JSOs) in every Salesian TVET institution. JSOs provide CV coaching, interview preparation, industrial internship placements, and graduate tracer studies through the digital Inserjeune platform, achieving a 57% direct placement rate.',
    icon: 'Briefcase',
    keyPillars: [
      'Dedicated Job Service Officers in 15 provinces',
      'Inserjeune digital graduate tracer tracking',
      'Corporate partnerships with 500+ regional employers',
      'Incubation & startup micro-grants for young entrepreneurs',
    ],
    objectives: [
      'Dedicated, trained Job Service Officers (JSOs) stationed at each provincial TVET office',
      'Digital graduate tracking and labor market intelligence via the Inserjeune platform',
      'Corporate MoUs and apprenticeship agreements with 500+ leading regional employers',
      'Business incubation, toolkits, and startup micro-financing for youth entrepreneurs',
    ],
    keyMetrics: [
      { value: '57%+', label: 'Employment Rate', description: 'Verified within 6-12 months of graduation' },
      { value: '500+', label: 'Employer Partners', description: 'Offering direct apprenticeships and hires' },
      { value: '15', label: 'Provincial JSO Hubs', description: 'Coordinating regional placement networks' },
    ],
    impactMetric: '57%+',
    impactLabel: 'Verified Graduate Job Placement Rate',
  },
  {
    id: 'green-sustainable-tvet',
    slug: 'green-tvet',
    title: 'Green & Sustainable TVET',
    tagline: 'Leading Africa’s Green Transition & Renewable Skills',
    shortDesc: 'Mainstreaming renewable energy, solar photovoltaic installations, climate-smart water systems, and eco-friendly campus practices.',
    description: 'Mainstreaming renewable energy, solar photovoltaic installations, climate-smart water systems, and eco-friendly campus practices.',
    fullDesc: 'In partnership with the Don Bosco Green Alliance and international partners like BMZ and Jugend Eine Welt, DBTA is leading Africa’s green vocational revolution. We deliver specialized Solar PV courses, Solar Photovoltaic Water Pumping Systems (SPVWPS) certifications, and solar entrepreneurship training, preparing youth for the burgeoning green economy.',
    icon: 'Sun',
    keyPillars: [
      'Solar PV Installer & Technician Certification',
      'Solar Photovoltaic Water Pumping Systems (SPVWPS)',
      'Energy efficiency audits across TVET campuses',
      'Integration of circular economy & waste reduction',
    ],
    objectives: [
      'Certified Solar Photovoltaic (PV) installation and maintenance training labs',
      'Solar Photovoltaic Water Pumping Systems (SPVWPS) specialized curriculum for agriculture',
      'Institutional green campus policies: solarized power, rainwater harvesting, waste segregation',
      'Entrepreneurship mentorship in off-grid solar and clean-energy micro-enterprises',
    ],
    keyMetrics: [
      { value: '1,200+', label: 'Certified Solar Specialists', description: 'Trained and deployed across 8 target countries' },
      { value: '20+', label: 'Green Campus Labs', description: 'Equipped with solar testing benches and pumps' },
      { value: '40%', label: 'Female Enrollment', description: 'Target for women entering clean energy trades' },
    ],
    impactMetric: '1,200+',
    impactLabel: 'Certified Green & Solar Specialists',
  },
  {
    id: 'digital-skills',
    slug: 'digital-skills',
    title: 'Digital Skills & Innovation',
    tagline: 'Empowering Youth in the Fourth Industrial Revolution',
    shortDesc: 'Equipping youth with industrial automation, computer maintenance, coding, graphic communications, and digital literacy.',
    description: 'Equipping youth with industrial automation, computer maintenance, coding, graphic communications, and digital literacy.',
    fullDesc: 'Bridging the digital divide across Africa through modern computer labs, Cisco networking academies, and industrial IoT programs. DBTA provides young people from underprivileged backgrounds with the high-demand digital capabilities required in the Fourth Industrial Revolution.',
    icon: 'Wrench',
    keyPillars: [
      'Cisco Networking & Cybersecurity certification',
      'Industrial automation and programmable logic controllers (PLC)',
      'Digital literacy for marginalized young women and men',
      'Cloud and software development apprenticeships',
    ],
    objectives: [
      'Network engineering and cybersecurity certifications in partnership with Cisco Academies',
      'Industrial automation, PLC robotics, and computerized machine tooling',
      'Foundation digital literacy and IT support training for marginalized rural youth',
      'Digital learning repository access through DBTA Digital Library in 3 languages',
    ],
    keyMetrics: [
      { value: '15,000+', label: 'Youth Certified', description: 'In digital trade applications and networking' },
      { value: '2,500+', label: 'E-Textbooks & Manuals', description: 'Freely accessible on DBTA Digital Library' },
      { value: '119', label: 'Connected TVET Hubs', description: 'Equipped with computer laboratories' },
    ],
    impactMetric: '15,000+',
    impactLabel: 'Youth Digitally Certified',
  },
  {
    id: 'capacity-building',
    slug: 'capacity-building',
    title: 'Capacity Building & Teacher Training',
    tagline: 'Empowering Master Instructors & TVET Leadership',
    shortDesc: 'Continuous pedagogical and technical upskilling for TVET centre managers, instructors, and provincial coordinators.',
    description: 'Continuous pedagogical and technical upskilling for TVET centre managers, instructors, and provincial coordinators.',
    fullDesc: 'The quality of vocational training is inextricably linked to instructor competence. DBTA organizes continuous professional development workshops, pedagogical mastery seminars, and technical apprenticeships in collaboration with European and African polytechnic institutes, ensuring instructors master contemporary industrial methodologies.',
    icon: 'GraduationCap',
    keyPillars: [
      'Annual continental instructor training seminars',
      'Leadership & TVET governance mastery for principals',
      'Financial sustainability & resource mobilization training',
      'Modern competency-based assessment pedagogy',
    ],
    objectives: [
      'Continuous pedagogical upskilling in Competency-Based Education and Training (CBET)',
      'Industry immersion internships for TVET teachers to keep pace with new technologies',
      'Leadership, governance, and financial sustainability training for TVET Principals',
      'Training on Don Bosco Preventive System pedagogy in technical workshop environments',
    ],
    keyMetrics: [
      { value: '850+', label: 'Instructors Upskilled', description: 'Annually across continental workshops' },
      { value: '1:7', label: 'Staff-to-Student Ratio', description: 'Ensuring intense hands-on mentorship' },
      { value: '100%', label: 'Leadership Trained', description: 'In institutional governance and compliance' },
    ],
    impactMetric: '850+',
    impactLabel: 'TVET Instructors Upskilled Annually',
  },
  {
    id: 'recognition-of-prior-learning',
    slug: 'recognition-of-prior-learning',
    title: 'Recognition of Prior Learning (RPL)',
    tagline: 'Certifying Informal Artisans for Dignifying Livelihoods',
    shortDesc: 'Formalizing, assessing, and certifying the competencies of informal sector artisans and youth to unlock formal employment.',
    description: 'Formalizing, assessing, and certifying the competencies of informal sector artisans and youth to unlock formal employment.',
    fullDesc: 'Millions of African youth and master craftspeople possess world-class skills acquired through informal apprenticeships but lack formal credentials. DBTA works with national TVET authorities in Malawi, Burkina Faso, Kenya, and beyond to develop and implement standardized RPL assessment frameworks, transforming informal work into accredited professional status.',
    icon: 'Users',
    keyPillars: [
      'National TEVETA & RPL framework formulation',
      'Artisan skills assessment and gap training',
      'Official government-recognized certification',
      'Economic formalization and dignified wage advocacy',
    ],
    objectives: [
      'Advocating and partnering with national qualification authorities on RPL legal frameworks',
      'Conducting rigorous practical assessment of informal craftspeople and jua kali artisans',
      'Delivering targeted 2-to-4 week bridge training modules for theoretical competencies',
      'Issuing state-recognized national trade test certifications to unlock formal contracts',
    ],
    keyMetrics: [
      { value: '3,500+', label: 'Artisans Assessed', description: 'And certified across pilot countries' },
      { value: '200%', label: 'Income Growth', description: 'Reported by certified master craftspeople' },
      { value: '4', label: 'National Frameworks', description: 'Co-developed with qualification agencies' },
    ],
    impactMetric: '3,500+',
    impactLabel: 'Informal Artisans Certified',
  },
  {
    id: 'advocacy-partnerships',
    slug: 'advocacy-policy',
    title: 'Advocacy & Continental Policy',
    tagline: 'Shaping Pan-African TVET Strategies & Alliances',
    shortDesc: 'Advancing the domestication of the AU Continental TVET Strategy 2025–2034 and hosting the Annual Stakeholders Assembly.',
    description: 'Advancing the domestication of the AU Continental TVET Strategy 2025–2034 and hosting the Annual Stakeholders Assembly.',
    fullDesc: 'DBTA serves as a premier continental voice for technical education, engaging the African Union Commission, regional economic communities, and international development agencies. Through the Annual Stakeholders Assembly (ASA), DBTA convenes policymakers, industry leaders, and educators to shape youth employment policy across the continent.',
    icon: 'BookOpen',
    keyPillars: [
      'Annual Stakeholders Assembly (ASA)',
      'Domestication of the AU Continental TVET Strategy (2025–2034)',
      'Gender inclusion and vulnerable youth policy briefs',
      'Strategic bi-lateral and multi-lateral donor alliances',
    ],
    objectives: [
      'Organising the continental Annual Stakeholders Assembly (ASA) uniting key TVET leaders',
      'Domesticating and operationalising the African Union Continental TVET Strategy 2025–2034',
      'Publishing actionable research reports on youth migration, TVET financing, and gender equity',
      'Building enduring partnerships with BMZ, Don Bosco Mondo, Jugend Eine Welt, and EU agencies',
    ],
    keyMetrics: [
      { value: '35', label: 'Nations Represented', description: 'In continental governance conferences' },
      { value: '15', label: 'Research Papers', description: 'Published and shared with TVET ministries' },
      { value: '10+', label: 'Global Donors', description: 'Collaborating in multi-year funding pacts' },
    ],
    impactMetric: '35 Nations',
    impactLabel: 'Unified Under DBTA Network',
  },
];
