import { TradeBenchmark } from './types';

export const trades: TradeBenchmark[] = [
  {
    id: 'solar-pv',
    slug: 'solar-pv-microgrids',
    title: 'Renewable Energy & Solar PV Microgrids',
    shortTitle: 'Solar PV & Clean Energy',
    category: 'Clean Energy & Green',
    icon: 'Sun',
    curriculumFramework: 'DBTA Continental Green TVET Harmonized Curriculum (Level 3 - 5)',
    averageEmploymentRate: 86,
    totalAccreditedCentres: 34,
    annualTraineesTrained: 4200,
    topPerformingCentres: [
      {
        institutionId: 'db-boys-town-nairobi',
        institutionName: 'Don Bosco Boys Town Nairobi',
        countryName: 'Kenya',
        flagEmoji: '🇰🇪',
        placementRate: 91,
      },
      {
        institutionId: 'db-gatenga-kigali',
        institutionName: 'Don Bosco Gatenga TVET Center',
        countryName: 'Rwanda',
        flagEmoji: '🇷🇼',
        placementRate: 88,
      },
      {
        institutionId: 'db-ashaiman-accra',
        institutionName: 'Don Bosco Technical Institute Ashaiman',
        countryName: 'Ghana',
        flagEmoji: '🇬🇭',
        placementRate: 85,
      },
    ],
    leadIndustryPartner: 'Schneider Electric Foundation & BMZ Germany',
    description:
      'Pan-African flagship discipline preparing technicians in residential off-grid solar, commercial grid-tied systems, lithium battery storage, solar water pumping, and microgrid design.',
    laborDemandOutlook: 'Very High',
  },
  {
    id: 'automotive-mechatronics',
    slug: 'automotive-mechatronics',
    title: 'Automotive Engineering & Mechatronics',
    shortTitle: 'Automotive & Mechatronics',
    category: 'Industrial Engineering',
    icon: 'Cpu',
    curriculumFramework: 'Dual-TVET Diagnostic & Electro-Mobility Framework',
    averageEmploymentRate: 82,
    totalAccreditedCentres: 28,
    annualTraineesTrained: 3800,
    topPerformingCentres: [
      {
        institutionId: 'db-boys-town-nairobi',
        institutionName: 'Don Bosco Boys Town Nairobi',
        countryName: 'Kenya',
        flagEmoji: '🇰🇪',
        placementRate: 87,
      },
      {
        institutionId: 'db-salama-lubumbashi',
        institutionName: 'Institut Technique Salama',
        countryName: 'DRC',
        flagEmoji: '🇨🇩',
        placementRate: 84,
      },
      {
        institutionId: 'db-maputo-mozambique',
        institutionName: 'Instituto Técnico Dom Bosco Matola',
        countryName: 'Mozambique',
        flagEmoji: '🇲🇿',
        placementRate: 83,
      },
    ],
    leadIndustryPartner: 'Bosch Africa & Toyota Mobility Foundation',
    description:
      'Modern automotive diagnostics, electronic fuel injection (EFI), hybrid vehicle maintenance, heavy diesel equipment, and early-stage electric vehicle (EV) fleet conversions.',
    laborDemandOutlook: 'Very High',
  },
  {
    id: 'electrical-installation',
    slug: 'electrical-installation-automation',
    title: 'Industrial Electrical & Automation',
    shortTitle: 'Electrical & Automation',
    category: 'Industrial Engineering',
    icon: 'Zap',
    curriculumFramework: 'Harmonized Industrial Electrical & PLC Standard (Level 4)',
    averageEmploymentRate: 84,
    totalAccreditedCentres: 42,
    annualTraineesTrained: 5600,
    topPerformingCentres: [
      {
        institutionId: 'db-salama-lubumbashi',
        institutionName: 'Institut Technique Salama',
        countryName: 'DRC',
        flagEmoji: '🇨🇩',
        placementRate: 89,
      },
      {
        institutionId: 'db-ashaiman-accra',
        institutionName: 'Don Bosco Technical Institute Ashaiman',
        countryName: 'Ghana',
        flagEmoji: '🇬🇭',
        placementRate: 84,
      },
      {
        institutionId: 'db-onitsha-nigeria',
        institutionName: 'Don Bosco VTC Onitsha',
        countryName: 'Nigeria',
        flagEmoji: '🇳🇬',
        placementRate: 82,
      },
    ],
    leadIndustryPartner: 'Schneider Electric & Siemens Stiftung',
    description:
      'Comprehensive preparation in high and low voltage industrial distribution, motor control centers (MCC), programmable logic controllers (PLCs), and building automation systems.',
    laborDemandOutlook: 'High',
  },
  {
    id: 'ict-software',
    slug: 'ict-software-digital-infrastructure',
    title: 'ICT, Software Development & Cloud Networks',
    shortTitle: 'ICT & Cloud Networks',
    category: 'Digital & ICT',
    icon: 'Terminal',
    curriculumFramework: 'DBTA Cisco & Digital Skills Pan-African Syllabus',
    averageEmploymentRate: 79,
    totalAccreditedCentres: 24,
    annualTraineesTrained: 3200,
    topPerformingCentres: [
      {
        institutionId: 'db-gatenga-kigali',
        institutionName: 'Don Bosco Gatenga TVET Center',
        countryName: 'Rwanda',
        flagEmoji: '🇷🇼',
        placementRate: 85,
      },
      {
        institutionId: 'db-lilongwe-malawi',
        institutionName: 'Don Bosco Youth Technical Institute',
        countryName: 'Malawi',
        flagEmoji: '🇲🇼',
        placementRate: 82,
      },
      {
        institutionId: 'db-maputo-mozambique',
        institutionName: 'Instituto Técnico Dom Bosco Matola',
        countryName: 'Mozambique',
        flagEmoji: '🇲🇿',
        placementRate: 78,
      },
    ],
    leadIndustryPartner: 'Cisco Networking Academy & Microsoft Philanthropies',
    description:
      'Digital infrastructure skills covering CCNA network engineering, full-stack software development, cyber security fundamentals, cloud administration, and hardware maintenance.',
    laborDemandOutlook: 'Expanding',
  },
  {
    id: 'welding-fabrication',
    slug: 'welding-fabrication-metalwork',
    title: 'Advanced Welding & Structural Metal Fabrication',
    shortTitle: 'Welding & Fabrication',
    category: 'Industrial Engineering',
    icon: 'Flame',
    curriculumFramework: 'AWS/ISO 9606 Pipe & Plate Standard Harmonized Framework',
    averageEmploymentRate: 81,
    totalAccreditedCentres: 31,
    annualTraineesTrained: 3500,
    topPerformingCentres: [
      {
        institutionId: 'db-boys-town-nairobi',
        institutionName: 'Don Bosco Boys Town Nairobi',
        countryName: 'Kenya',
        flagEmoji: '🇰🇪',
        placementRate: 86,
      },
      {
        institutionId: 'db-onitsha-nigeria',
        institutionName: 'Don Bosco VTC Onitsha',
        countryName: 'Nigeria',
        flagEmoji: '🇳🇬',
        placementRate: 83,
      },
      {
        institutionId: 'db-maputo-mozambique',
        institutionName: 'Instituto Técnico Dom Bosco Matola',
        countryName: 'Mozambique',
        flagEmoji: '🇲🇿',
        placementRate: 81,
      },
    ],
    leadIndustryPartner: 'Fronius & Lincoln Electric Certified Labs',
    description:
      'Certified SMAW, TIG, and MIG/MAG welding for pipeline infrastructure, pressure vessels, maritime, and structural architectural installations.',
    laborDemandOutlook: 'High',
  },
  {
    id: 'agribusiness-food',
    slug: 'agribusiness-smart-farming',
    title: 'Agri-Tech, Hydroponics & Agro-Processing',
    shortTitle: 'Agri-Tech & Food Systems',
    category: 'Agribusiness & Food',
    icon: 'Sprout',
    curriculumFramework: 'Pan-African Sustainable Agro-Enterprise Framework',
    averageEmploymentRate: 76,
    totalAccreditedCentres: 20,
    annualTraineesTrained: 2900,
    topPerformingCentres: [
      {
        institutionId: 'db-fianarantsoa-madagascar',
        institutionName: 'CFP Don Bosco Fianarantsoa',
        countryName: 'Madagascar',
        flagEmoji: '🇲🇬',
        placementRate: 82,
      },
      {
        institutionId: 'db-palabek-uganda',
        institutionName: 'Don Bosco VTC Palabek',
        countryName: 'Uganda',
        flagEmoji: '🇺🇬',
        placementRate: 77,
      },
    ],
    leadIndustryPartner: 'FAO & VIS Volontariato Internazionale',
    description:
      'Climate-smart agriculture, solar-powered drip irrigation, organic greenhouse production, post-harvest grain management, and agricultural value-chain processing.',
    laborDemandOutlook: 'Very High',
  },
];
